### ISSUE TITLE
Remove Lockfiles Feature Flag and use feature by default

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#5984]

**Comment by aaronsteers** [comment]
Thanks for raising this, @edgarrmondragon! I've added to the project board.

Any other feature flags we should toggle? Does it make sense to widen this to cover any others as well?

**Comment by edgarrmondragon** [comment]
@aaronsteers 

> Any other feature flags we should toggle? Does it make sense to widen this to cover any others as well?

I think for the moment the other two (Uvicorn and Scheduled jobs in the API) are good to keep, unless @pandemicsyn thinks different 😄

**Comment by aaronsteers** [comment]
> Uvicorn and Scheduled jobs in the API

Thanks, @edgarrmondragon. For my part, I think (?) those should both stay off by default for now.

**Comment by pandemicsyn** [comment]
> Uvicorn and Scheduled jobs in the API

> Thanks, @edgarrmondragon. For my part, I think (?) those should both stay off by default for now.

+1

**Comment by cjohnhanson** [comment]
@edgarrmondragon @aaronsteers quick clarification: I'm reading this to mean that we want to *remove the feature flag entirely along with the checks around the relevant code paths*. Is that correct or do we just want to leave the feature flag in place but have it turned on by default so users can still toggle it off?

**Comment by tayloramurphy** [comment]
@aaronsteers @cjohnhanson I'm okay with the full removal approach. I'd initially thought it was just flipping the default, but I think it makes sense. For users that don't want to use lock files we could engage them and see a) why and b) if adding a toggle would make sense.

**Comment by cjohnhanson** [comment]
@aaronsteers  (CC: @edgarrmondragon) Checking in real quick--removing lockfiles continues to cause some issues in testing. There's a few approaches I could take here:
1. Go through regressions 1 by 1 and figure out what the desired behavior is that they reflect and whether or not that desired behavior has legitimately changed with lockfiles always on. Then update the tests to reflect the new desired behavior. This is what I'm currently doing.
1. Assume that new behavior with lockfiles is very likely to be the correct behavior and update tests accordingly without doing a full deep dive to grok the behavior the test is expecting. Obviously this introduces some risk but "in theory" if the lockfile tests are a thorough and correct representation of desired lockfile behavior and they are passing, then this should be relatively safe to assume.
1. Call an audible and instead of doing the "full removal" approach, just change to the "on by default" approach and then toggle lockfiles off for some of these failings tests. This obviously seems bad because what we're testing is then not the default behavior that new users will actually see, but I thought I'd raise it as a potential option anyway.
