### ISSUE TITLE
Verify release marker behaves as intended

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6021]
Per @aaronsteers  in https://github.com/meltano/meltano/pull/5978/files#r889606266 the release marker landing in #5978 maybe not always get packaged/distributed as intended:

> Python packaging is weird sometimes about what actually ships and what doesn't. Can we double check this file gets bundled and installed with the operation? (Either in docs or through a 'real' test.)

> Also - and I just realized this now - I think this breaks if a user does pipx install git+https://github.com/meltano/meltano.git

> For now, I think this can be a bug we would live with, but perhaps we open an issue to track/prioritize in a future PR.

**Comment by aaronsteers** [comment]
@pandemicsyn and @WillDaSilva - Did we have any progress here? I was reminded of this as I'm migrating the publish script from GitLab to GitHub.

Do we still need to run these lines or do we / can we just have this on by default until we have time to circle back?

```
    - pushd /meltano/dist
    - ARCHIVE="$(sh -c 'echo "$1"' sh meltano*.tar.gz)"
    - DIR="$(basename $ARCHIVE .tar.gz)"
    - tar -xvzf "$ARCHIVE"
    - touch "$DIR/src/meltano/core/tracking/.release_marker"
    - tar -cvzf "$ARCHIVE" "$DIR"
```

**Comment by WillDaSilva** [comment]
We probably just need to update Poetry's `include` field in `pyproject.toml` to include `.release_marker`.

**Comment by WillDaSilva** [comment]
@aaronsteers @pandemicsyn I've manually verified that `.release_marker` is included if the lines posted by @aaronsteers are run in CI to update the sdist before it is published to PyPI.

To deal with the `pipx` install from GitHub issue, we can probably flip this around: include a file in our git repository that gets removed by some code in CI that alters the sdist before it is published to PyPI. Basically the same code as above, but with `rm` instead of `touch`, and then negate the logic around the file being present or not. I guess we can call it `.dev_marker`.
