### ISSUE TITLE
Fix legacy CI pipeline

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6066]
Legacy `homepage_sample_code` CI tests are failing:

https://gitlab.com/meltano/legacy-ci/meltano/-/jobs/2554366162

Looks like an issue with deprecated `env_aliases`.

**Comment by DouweM** [comment]
Hmm, still broken after those PRs that I'd thought would fix it: https://gitlab.com/meltano/legacy-ci/meltano/-/jobs/2559650800

**Comment by DouweM** [comment]
The issue is in this line from the logs:

```
The profile 'meltano' does not have a target named 'target_postgres'. The valid target names for this profile are:
```

This means that on https://github.com/meltano/files-dbt/blob/main/bundle/transform/profile/profiles.yml#L5, `DBT_TARGET` is coming in as `target_postgres`. The default value for that [`target` setting](https://github.com/meltano/hub/blob/main/_data/meltano/transformers/dbt/dbt-labs.yml#L26) is `$MELTANO_LOAD__DIALECT`, which corresponds to the `_dialect` extra of the loader dbt is running with: https://docs.meltano.com/concepts/plugins#dialect-extra, which has a default value of `$MELTANO_LOADER_NAMESPACE`. That would be set to `target_postgres`, so this all lines up.

Except that `target-postgres` overrides its `dialect` to be `postgres`: https://github.com/meltano/hub/blob/main/_data/meltano/loaders/target-postgres/meltano.yml#L5.

So it appears that this is not sticking, or at least not making it properly to dbt.

Strangely, though, I cannot reproduce this locally yet, the env passed to dbt has `'DBT_TARGET': 'postgres'` as expected:

```
'DBT_TARGET': 'postgres', 'MELTANO_TRANSFORM_TARGET': 'postgres', 'DBT_SOURCE_SCHEMA': 'tap_gitlab', 'MELTANO_TRANSFORM_SOURCE_SCHEMA': 'tap_gitlab', 'DBT_TARGET_SCHEMA': 'analytics', 'MELTANO_TRANSFORM_TARGET_SCHEMA': 'analytics'
```

**Comment by DouweM** [comment]
Let's see if debug logging shows us anything in CI: https://github.com/meltano/meltano/pull/6085/commits

**Comment by DouweM** [comment]
I got it: we're not storing extras from plugin definitions in the lockfile, so when Meltano reads the base plugin definition there instead of looking it up from discovery or the hub, the `dialect: postgres` override is missing! This also applies to `target_schema`.
