### ISSUE TITLE
Python-based Plugin Architecture

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6130]
I think we have a path forward on python plugin architecture (https://gitlab.com/groups/meltano/-/epics/134#note_981098666) which does not require modifying Meltano itself (at least not in the first iterations).

Since `pip_url` for any repo can include multiple libraries, we can extend any plugins' capabilities by _adding_ a meltano-managed python tool to any plugin that needs capabilities. Then those capabilities just need to registered as CLI-executable and be mapped to `commands` and `capabilities` in the Meltano plugin definition.

## Example: registering dbt packages in `packages.yml`

Today we have custom code in Meltano that adds entries to `packages.yml` for dbt during `meltano add transform ...`. We could replace it as follows:

1. Create a new python tool called `meltano-dbt-helpers` with a registered CLI command `meltano-dbt-util add package`.
2. Add that package to the pipurl for all dbt plugins. E.g. `pip_url: dbt-snowflake meltano-dbt-helpers`.
3. Register commands in the package that leverage the helper. E.g. 
    ```
   commands:
     add-dep:
       command: meltano-dbt-util
       args: add package
   ```

Then from the CLI as a user:

```
meltano run dbt:add-dep dbt-util
```

Would add `dbt-util` to the package.

For "smarter" integrations, we just need a contract that pairs `capabilities` like `service` with expected commands, like `ui`, `up`, and `down`.

## Comparison with other approaches

The best part of this approach is that it doesn't require _any_ code changes in Meltano - we and community members could implement this today with existing features.

**Comment by DouweM** [comment]
@aaronsteers Great suggestion, and injecting custom code into the venv will go a long way to adding new Meltano-specific functionality and commands to tools. 

Our current plugin glue code (e.g. for [Airflow](https://github.com/meltano/meltano/blob/main/src/meltano/core/plugin/airflow.py#L134), [Singer taps](https://github.com/meltano/meltano/blob/main/src/meltano/core/plugin/singer/tap.py), [dbt](https://github.com/meltano/meltano/blob/main/src/meltano/core/plugin/dbt/base.py), [superset](https://github.com/meltano/meltano/blob/main/src/meltano/core/plugin/superset.py)) mostly sets up the execution environment by setting env vars, running initialization commands, and generating config files. All of that could likely be done from a custom executable that wraps the main executable and has access to the configuration environment variables/files injected by Meltano. That's similar to the `entrypoint: init.sh` paradigm seen in Docker(-compose).

**Comment by DouweM** [comment]
@aaronsteers Very interesting idea, but I think it deserves its own issue so we can keep this one focused on building new plugins with the current capabilities.

**Comment by pnadolny13** [comment]
@aaronsteers @DouweM I like this idea! I have a few plugins ideas that I can test this out on, maybe as part of hack day.

If I'm understanding so far, it sounds like for a first iteration I could create a python CLI app and either:

1. add it as a standalone plugin
2. append it to an existing plugin as part of the pip_url and reference the library's executable in the command definition. 

The downside being that for option 1 I cant call the glue plugin using the main plugin name i.e. I'd call `superset-util:do_some_util_thing` and for option 2 I'm able to call it using the main plugin name like `superset:do_some_util_thing` but then I risk a dependency conflict.

Later as a second iteration we might build a mechanism in Meltano to solve these challenges and allow us to append the glue code library to the main plugin so it accessible under the parents namespace AND gets installed in its own venv.

Am I understanding that correctly?

**Comment by pnadolny13** [comment]
I worked on something like this during hack day and although I dont have something totally functional, it mostly proved out the pattern. My repo is https://github.com/pnadolny13/superset_glue. I explored both the wrapper approach and a pre/post hook approach. I ended up using the pre/post only because it seemed simpler for someone not familiar with Meltano core. The wrapper approach needs to accept the commands (i.e `ui`) plus all other addition arguments (`db upgrade`) that could also be commands for Superset. Also maybe this isnt an issue but it felt weird to have Meltano run a subprocess that runs a subprocess of the actual python package, if someone tried to stop the execution we'd have to traverse multiple levels to gracefully exit without leaving Superset running, right? 

My thoughts on where this could go:
- Right now when we want to add glue code to Meltano we create an Invoker implementation for it like [Superset's](https://github.com/meltano/meltano/blob/main/src/meltano/core/plugin/superset.py) and it also gets registered with the [factory.py](https://github.com/meltano/meltano/blob/813c5f930eb95c32f84e6b57728718a7b471cca6/src/meltano/core/plugin/factory.py#L35). Then it seems like Meltano matches by name in order to know to run the custom code otherwise it uses the default. If we make something like an "ExternalInvoker" it can know to either run the pre/post via the installed external pip package or pass the executable path and commands through to the glue package as a wrapper to run it itself.
- I originally was passing a json dict as input to the plugin but found that to be redundant because all the configs are available as env vars. I instead only needed the `run_dir` so the glue has a temp workspace to write files/configs/etc. and also the `executable` path for the main plugin (i.e. Superset) because for many plugins the glue code will need to execute the main plugin to pre configure.
- It could make sense to install these as utility plugins using the `requires` setting like file bundles do now. Then I can either accept the default that comes with the main plugin (i.e. `superset_glue` variant `meltano`) or install another variant and just toggle something like a `support_utility` name to point it to my non-default glue plugin (i.e. `superset_glue` variant `pnadolny13`).

SDK:
- I was attempting to start splitting the glue code out so we can hide some stuff away in a future SDK to make it easier. For the user it would be ideal if you didnt need to worry about the Typer (or other CLI package) stuff or what methods to implement. Being handed something like https://github.com/pnadolny13/superset_glue/blob/main/superset_glue/sdk/base.py that just says "implement theses methods with what you want to run before/after". We can abstract the interface between Meltano and the SDK away completely so users dont need to worry about it if we change how/what we send.
- We can give some utility methods like [retrieving the config from env vars ](https://github.com/pnadolny13/superset_glue/blob/d56cf638b39fb2c9da69aaf35e18cc175b16462a/superset_glue/superset.py#L21), better more consistent ways to execute subprocesses (thats always a stumbling point for me), logging in an appropriate way because I wasnt sure how type.echo would look when mixed in with Meltano logs and would log levels be respected?, maybe common file cleanup methods, etc.
- The SDK should also have a simple cookie cutter like we have in the Singer SDK so the project structure is quickly set for you. I had to remember how to setup a poetry project and make it executable.

**Comment by WillDaSilva** [comment]
Copying over my comments from the Office Hours Zoom chat, regarding `service`:

> Could go systemd style: start/status/stop/restart 

i.e. `meltano service start my-service`

> I wonder if we could even just use systemd to manage these daemon utilities. It would handle log collection, startup/teardown conditions, dependencies, and more

It might be pretty elegant and powerful if we can offload the work here onto systemd and the `service` command. The catch would be that it would only work for systems that use systemd. We could get macOS support by wrapping `launchctl`, but I'm not sure the amount of work there would be worth it. I'm not sure what Windows would use natively. A quick check online suggests that https://nssm.cc/ is popular, which suggests that supporting Meltano services this way on Windows would be very difficult. I think it's safe to say this approach would only work for Linux distros that run systemd.

**Comment by DouweM** [comment]
This is related to https://github.com/meltano/internal-general/issues/404, where we're discussing bringing everything related to plugin support into the meltano/meltano repo, so that adding or improving plugin support doesn't require touching YAML in meltano/hub, a file bundle in meltano/files-*, and optionally glue code in meltano/meltano. That would also include the glue/support code we're discussing in this issue: it should be its own self-contained package that doesn't require someone to know how the rest of Meltano works, but it could live in the meltano/meltano repo under e.g. a top-level `plugins` directory, instead of in separate repos.

**Comment by pnadolny13** [comment]
I've been thinking about how this plugin architecture will look holistically and I'm wondering if theres been conversations about how we maintain these glue packages alongside the original package, file bundles, and the hub plugin definition. You all might already be on top of this, if so ignore me but wanted to flag it in case we haven't thought it through yet.

It starts to feel pretty clunky with all these pieces living separately. Taking Airflow for example we have:

1. The Airflow pip package itself https://github.com/apache/airflow
1. The Meltano Airflow files bundle https://github.com/meltano/files-airflow
1. The Hub plugin definition https://github.com/meltano/hub/blob/main/_data/meltano/orchestrators/airflow/apache.yml
1. And the soon to be new Meltano SDK built airflow glue code plugin with the integration logic

For a utility like the ssh tunnel its a little better because we dont need some of these things but its still worth thinking of the worse case.

It would be great to take a stab at consolidating some of this with the implementation of the SDK, or at least decide on a strategy so we can keep it in mind while we're building the SDK.

In a recent office hours, maybe 7/20/22, we talked about having plugins store their metadata in their own repo which would solve point 3. For point 2/4, would we be able to combine the glue code and file bundle somehow? Conceptually theyre both pip packages with supporting code but one gets installed into a venv and the other into your meltano project. I havent thought it through yet but I'd think that we'd be able to support that somehow.

If we could store the files bundle, plugin metadata, and glue code in the plugin repo then I think we'd have the ideal case where we only need to manage 1 + 4 and the plugin developer only needs to support a single repo.

@aaronsteers @pandemicsyn @tayloramurphy @DouweM what do you guys think?

**Comment by tayloramurphy** [comment]
@pnadolny13 that's part of the definition of done in https://github.com/meltano/meltano/issues/6398 basically we want to consolidate these multiple places into a single Airflow Extension (or whatever we call it). Let me know if that specific issue (or the dbt one #6434 ) needs more explanation.

**Comment by pnadolny13** [comment]
@tayloramurphy awesome youre on it! It might be clear to others but in https://github.com/meltano/meltano/issues/6398#issue-1301179856 it talks about trying to solve the multiple repos problem but its not explicitly part of the definition of done. Is that intentional for a first iteration? It might change the way that the SDK skeleton is designed.

The definition of done says 

>All of the Airflow-specific code is in its own package. We'll worry about the monorepo question separately

which might not mean all code + files + metadata. Its fine if its not included in the first iteration but maybe as part of the DoD we have a strategy defined for handling files and metadata, if its not implemented.

**Comment by tayloramurphy** [comment]
@pnadolny13 the monorepo question is about having meltano + extensions + hub/sdk in the same repo. I'll update the language to make it clear that all of the Airflow extension code should live in the same place.

**Comment by pandemicsyn** [comment]
@pnadolny13 @tayloramurphy  Based on my reading of the issues, I was sort of operating under the assumption that everything would be self-contained in the plugin/extension because at first glance that simplifies things. And asking users to install both files-airflow and airflow extension seems wasteful. But I'm just starting down the path of actually working on an actual airflow plugin the last few days - so might still run into hiccups.  

_For now_, the only thing i've kept separate is the actual management/install of the airflow package. 

That might end up varying by plugin, but I'm guessing NOT managing the install of the thing the plugin works with will be pretty common. i.e. A MySQL/Terraform/etc package probably isn't going to try to manage a local installation of the things. 

I realize that for some plugins (like Airflow) they might, in fact, want to do that - so we can add that once i have something actually working if really want that.

**Comment by tayloramurphy** [comment]
> I was sort of operating under the assumption that everything would be self-contained in the plugin/extension because at first glance that simplifies things

@pandemicsyn yep, you've got the right assumption. I've updated the description of the issue to call that out.

**Comment by pnadolny13** [comment]
@tayloramurphy I know theres that discussion about bring our packages meltano/hub/sdk into one repo but yeah I'm talking about bringing all components of a single plugin into one package like file bundle/plugin definition/glue code/package. That package could end up living in the meltano/meltano github namespace but as long as its 1 installable piece of code (or 2 like Airflow). Sounds like were on the same page.

**Comment by pnadolny13** [comment]
One other thing that I was thinking about recently related to this is the fact that sometimes having many repos is a pain especially for a small piece of code like these glue plugins might be. Especially because lots of people are doing custom things that arent going to be useful outside their context, so theyre the only ones installing their package.

I wonder if we considered making the plugin SDK code something that lives within your project to start then it can be pushed up to a repo and the hub if and when its ready to be shared with the community. Theres pros and cons of this though. I think you can do this already with local references as the plugin executable but it might be something we build around.

Imagining how this would work:
- `meltano create plugin --path ./custom_plugins/utilities/my_sdk_util` which uses a cookie cutter to get your plugin structure started and installs the plugin as a utility into your meltano.yml.
- All commands, metadata, cabilities, etc are added for me.
- Immediately without writing code you should be able to invoke it using `meltano invoke my_sdk_util --help` or something similar. It executes but doesnt do anything.
- I write a chunk of code to do the thing I need to do. Including maybe adding some python dependencies.
- I have a fully functional plugin that I check into my git repository. Maybe I add it to a schedule. It solves my needs.
- Now I want to contribute it back to the community. I use it in prod and iterate on it, hardening and making more generically useful.
- I move it out of my project and into a pip installable github repo for sharing. Update my project configs to point to github.
- `meltano push_to_hub` I think theres already and issue around this but it pushes up my configs for this plugin to the hub.

The plugin SDK is essentially a way for users to write arbitrary python code to be run by meltano. I feel like the path were on right now assumes that theyre writing arbitrary AND generically useful python code. Allowing users to treat their Meltano project like a software project would include adding custom software packages to the project. Not all custom software needs to be packaged and installed, it can live within the "mono-repo" that is your meltano project. Our current pattern leans towards having all code live outside of the meltano project to be pip installed in for use so the meltano project only holds configs basically, this pattern would start to allow users to bring their custom code into the project.

I also want to make sure we're not accidentally going down the path that orchestrators are trying to get away from where in order to adopt a new tool you need to re-write your code using their semantics even though its the same python code and functionality i.e. Airflow DAGs to Dagster ops/solids (?). We'd want users to be able to just basically paste plain python into their projects and run it, they dont need to re-write to our semantics of creating a standalone repo, expose as a CLI, etc. It should just work by pasting python code in the right place.

@tayloramurphy what are your thoughts from a product perspective? @pandemicsyn from an engineering perspective?

**Comment by tayloramurphy** [comment]
@pnadolny13 thanks for your thoughts on this. I really like the user journey you've described here. Keeping it focused on the work they're doing is great. 

I think there's an opportunity for some interactive aspect too. If a user is trying to add an existing python package or containerized tool, we could ask that and have slightly different behavior - otherwise we just assume it's Python and roll with it. I _really_ like this idea! @pandemicsyn @aaronsteers would love your thoughts

**Comment by alex-harness** [comment]
@pnadolny13 

As a user, my response:
👀 🔥

**Comment by pnadolny13** [comment]
@tayloramurphy @pandemicsyn one other thing that came up in a conversation earlier that stuck with me is that we might be choosing to have the SDK plugin share a venv with the underlying parent package, in the case of a wrapper plugin like for Airflow/Superset/etc., but wouldnt that cause a dependency headache? I wouldn't want to write a SDK plugin thats at the mercy of the parent plugins dependencies which are out of my control. I cant recall what the advantages of sharing the venv were, other than saving space and install time, am I missing a larger advantage?

**Comment by WillDaSilva** [comment]
> I cant recall what the advantages of sharing the venv were, other than saving space and install time, am I missing a larger advantage?

@pnadolny13 The install-time advantage isn't even all that large in most cases, since any deps that could be re-used would be cached anyway after the parent plugin downloads it.

**Comment by pandemicsyn** [comment]
@tayloramurphy was mentioning to @aaronsteers that I'm just about ready to break out the extension sdk into its own repo and package. So we have to tackle the hardest challenge in product dev...naming things.

What do we want to name the extension sdk package and repo? And are we ok with the term "extensions"? 

@aaronsteers in our offline convo, you had an idea around calling it the `edk/extension developer kit` and the singer sdk the `cdk/connector developer kit` that sounded really good.

**Comment by tayloramurphy** [comment]
> edk/extension developer kit and the singer sdk the cdk/connector developer kit 

I like EDK for the extension side. If we go with components for the actual tools themselves, the extension is the glue code for those components. Component developer kit _wouldn't_ make sense b/c we're generally not developing the components themselves.

I'm hesitant to change the name to CDK for the singer piece b/c everything we've had for nearly 2 years is with `SDK`. I'd rather we update how we talk about it than change the abbreviation. Plus a certain other company (A*rbyte) uses CDK as well. @emilylucie what's your marketing take on this?

**Comment by pandemicsyn** [comment]
@tayloramurphy so for the sdk we currently have:

- the repo: `http://github.com/meltano/sdk`
- the package name: `singer-sdk` & `singer_sdk`

So for this new addition, maybe something like:

- the repo: `http://github.com/meltano/edk`
- the package name: `meltano-edk` & `meltano_edk`

**Comment by tayloramurphy** [comment]
@pandemicsyn LGTM :shipit:

**Comment by aaronsteers** [comment]
> I like EDK for the extension side. If we go with components for the actual tools themselves, the extension is the glue code for those components. Component developer kit wouldn't make sense b/c we're generally not developing the components themselves.

Agreed on this point. Whatever we call the plugins or components or tools, or orchestrators, etc., the `extension` is the thing that brings compatibility with the component as a whole and isn't necessarily interchangeable with it.

E.g.: 

> Meltano supports `dbt` as a component/plugin/tool/transformer. When you install `dbt` into your project, Meltano will also install the Meltano DBT extension `dbt-ext`. 

> The legacy `airflow` plugin doesn't have a corresponding extension and didn't need one because that code was built into Meltano itself.

The language seems intuitive to me without being overly technical or jargon-y.

**Comment by tayloramurphy** [comment]
@aaronsteers love the copy examples. FYI @emilylucie as we'll have to update language in places.

**Comment by pandemicsyn** [comment]
fyi - Setup https://github.com/meltano/edk to house the extension ~~sdk~~ edk.

**Comment by ReubenFrankel** [comment]
This sounds really cool! We were just thinking about the concept of hooks within meltano the other day - namely how it would be great if there was some interface for orchestrators to hook onto events like adding a schedule. The EDK sounds like it could offer something like that! :+1:

**Comment by aaronsteers** [comment]
@ReubenFrankel - Exactly. We'll be piloting the orchestration paradigm with `airflow`, then `cron`, and likely `dagster` soon. Collectively, those should give a pretty good framing for build-your-own or bring-your-own orchestration. 👍

**Comment by tayloramurphy** [comment]
Closing as we have multiple EDK examples on the Hub now 🎉 

* [EDK Repo](https://github.com/meltano/edk)
* [Airflow EDK Preview](https://hub.meltano.com/utilities/airflow)
* [dbt EDK Preview(s)](https://hub.meltano.com/utilities/)
* [Superset EDK Preview](https://hub.meltano.com/utilities/superset--meltano)
