### ISSUE TITLE
meltano run should not require a command to execute a plugin

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6188]
Per https://github.com/meltano/meltano/pull/6121#discussion_r895929389 it should be a simple change.

From @pandemicsyn the code is likely in https://github.com/meltano/meltano/blob/dfd9650170ff97fd69fdff7ac8dc7dc0841bf663/src/meltano/core/block/singer.py#L97 and we would need a docs update with this as well.

**Comment by tayloramurphy** [comment]
@aaronsteers I've added to Iteration 6 since this is a small change.

**Comment by cjohnhanson** [comment]
FYI @tayloramurphy I've got a little extra capacity this week so I'll plan on picking this up unless there's another more urgent unassigned issue that I can tackle in this iteration.

**Comment by tayloramurphy** [comment]
@cjohnhanson perfect thanks for the ping. Anything that's in the iteration but not assigned should be ready to be picked up by anyone!

**Comment by cjohnhanson** [comment]
@tayloramurphy following up here on [this comment in the PR](https://github.com/meltano/meltano/pull/6431#pullrequestreview-1040814529) since I think it potentially changes scope here.

As-is the PR allows plugin commands to be invoked as a block in `meltano run` without needing to provide a command. In the case where no command is provided, the bare CLI command is run. So if you were to run `meltano run tap-github target-postgres dbt-postgres`, it would just run the `dbt-postgres` top-level command, which just prints dbt's help message and then exits. This means in order to actually run `dbt-postgres run`, a user would still need to specify `dbt-postgres:run` as part of their job definition or in their arguments to `meltano run`. 

If we want to have a bare `dbt-postgres` block be interpreted as `dbt-postgres run`, we would need to do one of the following:
1. Update plugin definitions to allow for a "default" command that gets run whenever no command is provided and then update the dbt plugin definitions in the hub to provide `run` as the default command
1. Specifically hard-code bare dbt blocks to tack on the `run` command.

**Comment by tayloramurphy** [comment]
> If we want to have a bare dbt-postgres block be interpreted as dbt-postgres run

@cjohnhanson I don't think we want that. That assumes too much for the user. dbt isn't a great example for why not having a command is valuable, but imagine if there's just a bare python script or even a docker container that just needs to be invoked w/o any commands. For all of the dbt plugins we've already specified the [dbt:run command](https://hub.meltano.com/transformers/dbt-postgres#command-run) but this just unlocks `meltano run` to be even more flexibile for arbitrary plugins. 

I do like the idea of a "default" command though and perhaps that can be explored in #6130

**Comment by cjohnhanson** [comment]
@tayloramurphy thanks for the clarification -- I was worried I had misunderstood the scope here but it sounds like we're on the same page.

The existing PR behaves as you described (no default command or "aliasing" of bare commands to some subcommand). Any thoughts on a good example of a plugin without a command to include in the docs? If not, I'll use the example of a bare python script.
