### ISSUE TITLE
Telemetry - Custom vs Hub plugins

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6201]
Add a flag to the plugin context to discern custom plugins from ones added from MeltanoHub.

**Comment by pnadolny13** [comment]
Digging up some info on this - I see this thread where the issue was linked https://github.com/meltano/meltano/pull/6114/files/316201d7b7379ba4392976fa211723ca11adc923#r898338811.

Right now the `variant` attribute is the proxy for understanding if a plugin is from the hub. A related challenge that comes to mind with this is the `original` variant problem that we have with our telemetry data. See:
- https://github.com/meltano/internal-data/discussions/7
- https://github.com/meltano/internal-data/issues/45

Those are private discussions but basically if someone doesnt have a variant name in their meltano.yml then its hard for us to associate its usage with the listing on the hub. I think original in this case could mean custom or from the hub which makes it hard to decipher. The telemetry data is viewed as either custom I wonder if this issue would help solve that problem. If we have a way to determine if the plugins is from the hub then we can assign a variant instead of `original` and flag it in the telemetry.
