### ISSUE TITLE
Add compile-time verification of built-in Meltano settings names

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6234]
Via enum or constants or a similar approach, we should ensure that functionality is not dependent upon correct spelling of string settings.

This is in follow up to a bug that was discovered on https://github.com/meltano/meltano/pull/6199#issuecomment-1159235493 due to misspelling of `disable_tracking` vs `tracking_disabled`.

There'd be two parts to this:

1. Adopt the approach we are using now for naming feature flags, which ensures that mispellings are not possible without a compile-time failure.
2. Create a unit test to ensure that the `settings.yml` filed does not include anything that the enum doesn't, and vice versa.

**Comment by aaronsteers** [comment]
@WillDaSilva - it's a good point but I was thinking we could also modify the type signature on the get method to accept/expect the enum class instead of a string. While it might still "work" by passing a string, we should be able to get mypy to fail CI checks in those cases where a string is passed directly. (And the dev would see a linter warning in their IDE.)

What do you think?

**Comment by WillDaSilva** [comment]
@aaronsteers I think we're locked into accepting strings in `SettingsService.get_with_metadata` and all of the functions that ultimately call it, but maybe we're going about this the wrong way. What we ultimately want here is an assurance that we'll know if a setting name is misspelled. We can alter the first few lines of `SettingsService.get_with_metadata` like so:

```python
        try:
            setting_def = setting_def or self.find_setting(name)
        except SettingMissingError:
            warn(name)
```

This emits a warning whenever a setting uses the default value, which is true whenever a setting name as been misspelled. Running the tests with this change produces just 4 warnings:

```
tests/meltano/core/test_project_settings_service.py::TestProjectSettingsService::test_feature_flag_allowed
  /home/will/meltano/meltano2/src/meltano/core/settings_service.py:335: UserWarning: ff.allowed
    warn(name)

tests/meltano/core/test_project_settings_service.py::TestProjectSettingsService::test_feature_flag_disallowed
  /home/will/meltano/meltano2/src/meltano/core/settings_service.py:335: UserWarning: ff.disallowed
    warn(name)

tests/meltano/core/test_project_settings_service.py::TestProjectSettingsService::test_strict_env_var_mode_on_raises_error
tests/meltano/core/test_project_settings_service.py::TestProjectSettingsService::test_strict_env_var_mode_off_no_raise_error
  /home/will/meltano/meltano2/src/meltano/core/settings_service.py:335: UserWarning: stacked_env_var
    warn(name)
```

We can probably update those 4 calls to check before calling, or explicitly request the default with `source=SettingValueStore.DEFAULT`. Then we can emit a warning whenever a setting is misspelled or otherwise not found. Since our tests no longer emit any warnings as of #6293, a warning raised for this reason should be fairly noticeable, and would greatly reduce the odds of us merging in any changes with a misspelling in a setting name.

We can also go further by adding a keyword argument `strict=False`, which when `True` to raise an exception instead of a warning. In a future version of Meltano we can make a breaking change by making the keyword argument default to `True` instead.

**Comment by aaronsteers** [comment]
I just checked the codebase. Most of the actual instances of string refs are using `.get(` and I see 34 results for as search for `settings_service.get("` which is the get() method and the start of a quoted string. At least a few others have dicts immediately above declaring a set of string values and then iterating through them in `settings_service.get(`.

We could take a couple different directions here, such as a new named command for `get_builtin()` or similar that only takes a type of the enum class, but I do think it's worth translating these from bare strings to enums, and adding a unit test to make sure the list of known enum values are exactly the same set as we declare in `settings.yaml`. (Extras on either side should probably indicate an error.)

**Comment by WillDaSilva** [comment]
I considered this approach, as well as using a keyword argument to force an enum value to be provided, but they suffer from the problem of being easily ignorable. By using the approach I describe in https://github.com/meltano/meltano/issues/6234#issuecomment-1171583989 we can't ignore typos, as they result in warnings/exceptions being raised.

I can still add an enum for the builtin settings, but that would only be there for the benefit of our editor autocompletors.
