### ISSUE TITLE
Video Tutorial: Deploy Meltano with Docker on AWS (prev k8s)

### ISSUE THREAD

**Issue by afolson** [meltano/meltano#6266]
There should be a guide on deploying using Kubernetes. I think we should assume that folks are familiar with Meltano and have a working project that they'd like to deploy. If they don't have a working project and just want to see how this works, we can link them to an example project that they can follow along with.

Out of scope:
- We can pick one hosting provider to deploy to but won't assist users with deploying to other providers at this time. (I'll open issues for those providers as we get requests for them)
- We're not going to help folks harden their server and meet data protection requirements, but if there are things that folks should know about those we should link them to additional resources. Ex. We can't tell them how to meet HIPAA, GDPR, or CCPA requirements for this deployment, but we can mention that they should be aware of local data protections and regulations before putting any data in the cloud.

**Comment by tayloramurphy** [comment]
@afolson confirming that the scope of this would be:

* A new tutorial in https://docs.meltano.com/tutorials/
* Focused on deploying Meltano via k8s likely on AWS

A goal of this should be that if @DouweM were to follow the instructions with a fresh Meltano project he could get it up and running in AWS on kubernetes.

@aaronsteers I've put this in **Iteration 7** and I'm assuming Ken would make sense for this, but want to confirm you're cool with the scope. Anything else you'd like to see?

**Comment by afolson** [comment]
@tayloramurphy Yeah that sounds good to me. Thanks!

**Comment by tayloramurphy** [comment]
@aaronsteers assigning to Ken for Iteration 7.

**Comment by aaronsteers** [comment]
Noted in conversation with @kgpayne - this is an `8` but only if we use exactly the process we have now for squared.

@kgpayne - Can you put some quick bullets inline in a comment about what the process would approximately look like, and any "rough edges" a user would run into?

**Comment by tayloramurphy** [comment]
Pushing to Iteration 11 since this won't be done before Ken's PTO.

**Comment by aaronsteers** [comment]
After speaking with @kgpayne , I took the following observations:

- Our Meltano Helm chart as of now does not include the backend database or a way to run Meltano jobs.
- As of now it deploys a single container with Meltano UI.
- We would basically need to rebuild the Helm chart and/or redesign it's dependencies to work as a pure K8 offering.
- The distinction to make is that as of now we are using Helm in concert with native AWS services, which means we do not have a portable Helm solution to deploy generically.

**Comment by tayloramurphy** [comment]
@aaronsteers the goal from the DevRel side was to get some content on how folks can/should deploy Meltano today. 

If there are too many issues with the current setup then it doesn't make sense to point folks down this path. It would be helpful though to have _something_ around deployment - even it's a "1 big box" solution that we know isn't perfect.

**Comment by tayloramurphy** [comment]
We have a community member that is working on a "MDS in a box" with DuckDB and Meltano (see https://github.com/matsonj/nba-monte-carlo). Perhaps we can extend this project (and their upcoming blog post) to take what they've done and put it into production via Docker and EC2. Not ideal but likely a better walkthrough than https://docs.meltano.com/guide/production

@sbalnojan do you think you'd be able to run with that or would you still prefer to get help from Engineering on this one? @kgpayne @aaronsteers thoughts on a more limited scope? We could even just record a video of containerizing it and putting it on AWS.

**Comment by aaronsteers** [comment]
I love the "bring nothing" approach that we can deliver with duckdb and I'm definitely in favor of moving in this direction for a demo tutorial and demo video.

I don't think this checks any boxes in regards to "production deployment" but we can come up with another top-line description for the solution.

I think we have a few paths here:

1. POC deployment: single large-sized container or ec2 would work but we still probably need an RDS backend for state tracking.
2. Quick Tutorials and "Quickstart Templates": this is where I think the duckdb solution fits. Super valuable but the emphasis is getting all features showcased in a turn-key implementation, rather than taking an existing project and productionalizing it.
3. Prod deployment: that's what we were aiming for with k8, but it's not ready for prime time yet (as discussed above) and as of now we don't have anything else "off the shelf" that's going to fit a larger number of use cases without violating tons of best practices (not just performance-wise but also security-wise, since this generally requires leaving open database ports, http ports, and/or ssh ports). A prod solution also has to have a method to get new updates from `main` and new security patches without breaking the environment, which aren't trivial challenges.


We have a decent path for 1 (POC) but I don't know if it's the right thing to prioritize. We can do 2 (Quickstart) and I think we should. For 3 (productionalizing) we don't have a turn-key solution, a better investment may be a guide "in plain speak" of what to look out for and how to approach production deployment in general. That would be a document and less so a step-by-step walkthrough. Taken as a generic guide, there are probably several of us on the engineering team who could help draft it if we want to scrap the existing and start from a clean slate. By writing it generically, it could also in theory be helpful to a large number of folks regardless of which cloud they are using.

What do you think?

**Comment by sbalnojan** [comment]
@tayloramurphy @aaronsteers sounds like this issue got carried off track. Maybe we should split these topics apart.


(1) In terms of PoC deployment I would suggest we (engineering) builds a pre-baked AMI, as a lot of tools with this requirement chain have (Tableau, Redash: https://redash.io/help/open-source/setup#aws). This way it truly is a "one-click" deployment at least for AWS customers. @aaronsteers why do we need the RDS? That's not apparent to me.

(2) On language: I think we should stop talking about "deploy with docker" alone. Docker is just a vehicle to deploy onto X, and the crucial parts about deployment are usually not docker, but rather the X, which could be ECS, an AMI, kubernetes (if it's on EKS we would need to be more specific again,...), ...

(3) I think @aaronsteers is right in that we need proper "How to deploy Meltano on AWS" kind of guides as well as discussions on our proposed deployment architecture. I'm not sure we even have these figure out yet, but I do believe we need to start somewhere.  

(4) Did I get it right that we think walking people through our deployment isn't a good idea? Because I just had a new user that stumbled over it where a video would've been helpful IMHO.

**Comment by afolson** [comment]
Just FYI we have the start of a deploy with docker guide here: https://docs.google.com/document/d/1V8hgCDHa1wMUBeuPSqlak82kT9RjrhNUJ07WvKwFkb4/edit#heading=h.rqyhntmp4ccd
