### ISSUE TITLE
Remove `click-default-group` dependency

### ISSUE THREAD

**Issue by dingobar** [meltano/meltano#6280]
Seems like this dependency has been abandoned since 2019, and is stopping upgrade to `click` >= 8, see https://github.com/meltano/meltano/issues/6264#issuecomment-1165360335 .

Suggest removing the dependency altogether because it contains literally just two classes and < 100 lines of code in total. We can probably just adopt it into the meltano codebase if it's important to have it.

**Comment by WillDaSilva** [comment]
You're right that [`click-default-group`](https://github.com/click-contrib/click-default-group) is no longer maintained, and does not officially support `click>=8`, but it does seem to work with `click>=8`.

Bringing their code into the Meltano repository and distributing it as part of the Meltano package would require proper attribution (licensing concerns), the integration of our test suites, and improvements to their tests. Forking their project would require we fix the various problems with it that currently exist, then publish it under a new name and provide ongoing maintenance.

Because of that and "if it ain't broke, don't break it", I'm leaning towards continuing to use `click-default-group` as-is, at least until a problem actually does arise from it.

Thoughts @edgarrmondragon @dingobar?

If there are no objections, I'll close this issue as not planned.

**Comment by edgarrmondragon** [comment]
@WillDaSilva Yeah. If it works fine with `click>=8`, let's keep it as long as we can.

**Comment by dingobar** [comment]
Completely agree 👍
