### ISSUE TITLE
Provide mechanism for printing/exporting a plugins environment variables

### ISSUE THREAD

**Issue by kgpayne** [meltano/meltano#6363]
Similar to `meltano config <plugin name>`, which allows users to "view the plugin's current configuration", it would be helpful when testing and debugging to be able to "view the plugins' current environment".

Currently this information is only accessible to end users via a log line with the `--log-level=debug` option when using run/elt/invoke.

**Comment by tayloramurphy** [comment]
@kgpayne I like this. Something like:

`meltano config environment <environment_name>` would be a good iteration. 

We could also do `meltano --environment= config <plugin_name>`. Looking at that now I'm not a huge fan of not having a verb after it for viewing 🤔

**Comment by kgpayne** [comment]
Still relevant, and potentially somewhat easier to implement with the recent manifest work 🤔 What do you think @WillDaSilva ?

**Comment by WillDaSilva** [comment]
@kgpayne This should be considerably easier to implement now that we have manifest, although work on the manifest ended prematurely so that we could focus on Meltano Cloud, and it has some known issues that should be addressed before we rely on it for such things:
- https://github.com/meltano/meltano/issues/7306
- https://github.com/meltano/meltano/issues/7355
- https://github.com/meltano/meltano/issues/7270
