### ISSUE TITLE
Add ability to provide custom `--state-id-suffix` to `meltano run`

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6370]
One thing that was cut late in development when adding incremental job support to `meltano run` was the ability to add a custom prefix to the auto generated job (now `state`) names: https://gitlab.com/meltano/meltano/-/merge_requests/2544#note_855957749

> I think we've agreed on this already but just want to reiterate given that we've just logged [ADR: Refactor/rename "job_id" as "state-id" (#3290 - closed)](https://github.com/meltano/meltano/-/issues/3290), it is probably best to try to avoid user config/override for the state_id_prefix or job_id_prefix. Just for the reason that if we allow them to configure the naming convention, and then we update what it is called, that will create a breaking change which I think it's best to avoid.

Now that the `job` -> `state` transition work has basically wrapped up we could revisit adding this.

@tayloramurphy fwiw this is a pretty easy-peasy change on the dev side. If only configurable as a cli arg weights probably as low as a 2, but if we want to also support this as a per env meltano.yml option than most likely more realistically a weight of 4.

**Comment by ReubenFrankel** [comment]
+1 on this. At the moment, we are creating a temporary environment per (our concept of a) pipeline as a workaround.

```sh
MELTANO_ENVIRONMENT=<pipeline_id>
meltano add environment "$MELTANO_ENVIRONMENT"

export MELTANO_ENVIRONMENT

meltano run ...
```

**Comment by ReubenFrankel** [comment]
I have an implementation for this working locally, but I'm away on holiday for 2 weeks now so I'll open a PR when I'm back. Until then, a few things:

"prefix" implies before other components of the state ID (i.e. `{prefix}-{active environment name}:{extractor name}-to-{loader name}`), but this causes errors when resolving state by environment since it seems to take everything before `:` as the environment name. Moving it to after the `:` (i.e. `{active environment name}:{prefix}-{extractor name}-to-{loader name}`) works, but then it's not a true prefix anymore.

Given the first format is preferred, the regex used to destructure information from the state ID will need to be modified a bit. Perhaps this is a bit easier if the prefix and environment name have a more distinct delimiter like `--`.

```
({prefix}--){active environment name}:{extractor name}-to-{loader name}
```

Given the second format is preferred, the option name may need some rethinking. A distinct delimiter might be desirable here as well.

```
{active environment name}:({prefix}--){extractor name}-to-{loader name}
```

**Comment by pandemicsyn** [comment]
@ReubenFrankel @aaronsteers I'm actually ok with the second option/format. In that case I think we could just use ":" as another deliminator and basically use that as our "official" segment key. 

Strictly speaking, does it *have to* be a prefix though? What if it was a suffix:

`{active environment name}:{extractor name}-to-{loader name}:{optional-suffix}` 

That's super easy to split on or abuse via regex, predictable, and still allows users to inject a unique attribute.

**Comment by ReubenFrankel** [comment]
@pandemicsyn Like the idea of `:` as a common segement delimiter, although there would have to be enforcement of a limited character-set for the prefix value.

Don't see why a postfix/suffix couldn't work also as `--state-id-postfix` or `--state-id-suffix`.

```
{active environment name}:{extractor name}-to-{loader name}(:{postfix/suffix}
```

As long as the option is clearer how it modifies the state ID, I don't see a problem.

**Comment by aaronsteers** [comment]
@ReubenFrankel and @pandemicsyn - I'm inclined to agree with the suffix approach and using `':'` as a delimiter.

Agreed this means we should disallow ':' from within the provided suffix _and_ from within the component parts, namely: `environment_name`, `extractor_name`, `loader_name`. (Shouldn't be a problem.)

**Comment by aaronsteers** [comment]
What I'm not sure about as of now is whether we should be mapping this to #6164.

@ReubenFrankel - Are your use cases for wanting this in line with #6164, or specifically, the use case of wanting to run 'basically' the same pipeline but with different seeds passed via env vars?

**Comment by ReubenFrankel** [comment]
@aaronsteers Yes, that is basically our requirement. This issue and #6164 sound very similar to me (even so far as mentioning `:` delimiting and the concept of a suffix in your initial comment), with the latter detailing more on how this would integrate with `meltano.yml` and environment variable expansion.

If I understand correctly, these two approaches would be equivalent:

- ```yml
  environments:
    dev:
      state_id_suffix: ${PIPELINE_ID}
      # ...
  ```
  
  ```
  meltano run ...
  ```

- ```
  meltano run --state-id-suffix $PIPELINE_ID ...
  ```

Either approach satisfies our use-case, but we lean more towards the CLI due to how we run meltano currently.

**Comment by aaronsteers** [comment]
@ReubenFrankel - Yes, exactly. And thanks for confirming regarding your use case related to #6164. 

We could then take an approach of:

1. Add `--state-id-suffix` support in `meltano run`.
2. Add `state_id_suffix: SUFFIX` support in `meltano.yml` environment definitions (as sampled in @ReubenFrankel's example code above), and support the setting of this via the `meltano config` CLI.
3. Long-term,  how these are used and what additional features we'd want (if at all) in a more 'native' meltano construct for something like "sub-environments" or "environment matrices".

The only disadvantage I can see about this ordering, and not going directly into the `meltano.yml` approach, is that presumably this introduces some _small_ additional risk of environments being misconfigured. I'd like to eventually land on a spec that gives a very high confidence that each config item in the matrix is properly set to match the others. That's something though, I think we can continue to iterate upon.

@tayloramurphy - From the product side, what do you think of this approach of these three steps, green-lighting the first two steps above and holding on the third longer-term question until we get usage data from the first two?

**Comment by tayloramurphy** [comment]
@aaronsteers looking at this proposal, yes I think it makes sense for the first 2 👍 Along with the spec that the suffix is delimited with `:` and we disallow ':' from within the provided suffix and from within the component parts.

We'd need to spend a moment on how environment variable inheritance works to make sure it's clear to user (similar to what Cody did in https://docs.meltano.com/guide/configuration#environment-variable-expansion ). Otherwise I like it
