### ISSUE TITLE
target-redshift process prevents deleted files to be removed from disk

### ISSUE THREAD

**Issue by halilduygulu** [meltano/meltano#6384]
Hi, when using target-redshift (wise) with meltano, I noticed disk usage on k8s node is increasing all the time even though /tmp folder and other places including / (root) folder is not growing in size. 

After checking with `lsof` tool, you can see deleted files are kept open(or something else) by target-redshift process so they are not actually removed from disk, so I ran out of 100gb disk space on k8s node even-though pod is using less than 10gb.

Sample from output of lsof, there are 100+ files like this
```
target-re  160             root   54u      REG               0,79 244794493  147626721 /tmp/public-mytable_1qhpq7op.csv.3 (deleted)
target-re  160             root   55u      REG               0,79 244865304  147626722 /tmp/public-mytable_k0fcdklp.csv.4 (deleted)
target-re  160             root   56u      REG               0,79 245068385  147626736 /tmp/public-mytable_scj5v0oc.csv.2 (deleted)
target-re  160             root   57u      REG               0,79 244919191  147626725 /tmp/public-mytable_l3ozw88o.csv.3 (deleted)
target-re  160             root   58u      REG               0,79 244815828  147626726 /tmp/public-mytable_v_uerrdh.csv.4 (deleted)
```

**Comment by tayloramurphy** [comment]
@halilduygulu that sounds like it might be specific to target-redshift. @pandemicsyn anything else we can ask for on our end to suss out whether it's a Meltano or plugin problem?

**Comment by pandemicsyn** [comment]
>  @pandemicsyn anything else we can ask for on our end to suss out whether it's a Meltano or plugin problem?

I thinks that's pretty firmly a plugin issue. The file is already marked deleted but the inodes still present because the process is still active and has an open file-descriptor for the file. 

Not really familiar with target-redshift but took a super quick glance (so fair warning this is more a guess), but at least at a glance, it looks like they never close (or save) the file-descriptor returned by mkstemp when creating the csv's:

https://github.com/transferwise/pipelinewise-target-redshift/blob/7e9e9e114452d2b33e02a0a911ee961c49f5ec5a/target_redshift/__init__.py#L407

**Comment by pandemicsyn** [comment]
target-redshift does call `os.remove` later but that would still keep the deleted file around until the process actually exited AND I think also means that you'd need the same amount of local disk space for temp storage as you're actually pushing to s3.

**Comment by tayloramurphy** [comment]
@halilduygulu I'm going to close this as it seems like it's a target-redshift issue.
