### ISSUE TITLE
feat: Refactor Airflow integration as an external Python plugin

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6398]
_This is a specific implementation issue for https://github.com/meltano/meltano/issues/6130 and is related to https://github.com/meltano/meltano/issues/6397_

### Problem to Solve

Much of the problems documented in #6397 are applicable to Airflow. Files and functionality related to Airflow are spread out across multiple repos:

* Meltano https://github.com/meltano/meltano/blob/main/src/meltano/core/plugin/airflow.py
* Files bundle https://github.com/meltano/files-airflow/
* Metadata definition on MeltanoHub https://hub.meltano.com/orchestrators/airflow

This is cumbersome and not contributor-friendly. Additionally, it's difficult to iterate on as it's not clear _where_, _how_, or even _what_ users should do to extend functionality - do they add a command? do they add something to Meltano? Should it be in the file bundle?

There's also the challenge of hooking into the capabilities of Meltano. As we expand what users can do with Meltano across multiple plugins, we dramatically increase the number of places we need to make an update when we update a capability or add additional functionality. 

We need to make it easy to add more plugins to Meltano and to iterate on their capabilities without users having to be aware of the internals of Meltano specifically. We'll start with Airflow & dbt. 

### Prior Art / Things to Keep in Mind

Refer to #6397 for some of the prior art around Superset, but there is a longer history of challenges users have with understanding our Airflow implementation.

* Original GitLab Epic https://gitlab.com/groups/meltano/-/epics/134#note_981098666
* Main meta-issue https://github.com/meltano/meltano/issues/6130 
* https://github.com/meltano/meltano/issues/6110

### Definition of Done

For this issue, there are a few items we'd need to see out of a first iteration. 

* All of the Airflow-specific code is in its own package and repository. We'll worry about the monorepo (whether extension code should live in the meltano/meltano repo) question separately
* This is built with the the skeleton of a true Meltano SDK in mind - bonus if the skeleton is started. This should also be built with Superset (#6397) and other generic plugins in mind.
* User functionality with Airflow is basically the same but there will likely be new generic capabilities either used or at least proposed
* Docs are updated in Meltano and the Hub on how the Airflow integration is used and changed 
* Hub updated to use new integration

**Comment by pandemicsyn** [comment]
@aaronsteers @tayloramurphy given:

> This is built with the the skeleton of a true Meltano SDK in mind - bonus if the skeleton is started. This should also be built with Superset (https://github.com/meltano/meltano/issues/6397) and other generic plugins in mind.

And comments like https://github.com/meltano/meltano/issues/6397#issuecomment-1180828662 in the Superset issue>

> I would agree that whoever is implementing it should be thinking about Airflow as well, but as the definition of done is an additional set of work for Airflow I'm inclined to to open a separate issue specifically for Airflow, cross-link, and make it clear in this issue that design decisions should be made with the context of Airflow (and likely other plugins) in mind.

Along with the fact that switching Airflow, dbt, and Superset are all ondeck back to back. I'm a little surprised that flushing out our plugin framework (ala https://github.com/meltano/meltano/issues/6130) and working within that context isn't more important and a higher priority. 

@aaronsteers building three quasi-external-plugins in a row seems like a very strong signal that we need to have our plugin arch spec in order.  

I think we should:

1. take a first pass at defining a spec/architecture approach in https://github.com/meltano/meltano/issues/6130
2. Implement and validate it using these Airflow, dbt, and Superset refactors
3. Revisit the spec after we've implemented Airflow, dbt, and Superset to  finalize the spec, log any follow up issues that arose during implementation, and log an ADR as needed. 

@tayloramurphy @aaronsteers if there are no objections to that, I'll head over to #6130 and drive that discussion before diving into this work to refactor the airflow integration.

**Comment by pandemicsyn** [comment]
@tayloramurphy fwiw, I think you nailed it for the product side and its mostly up to us (Engineering) to define the architecture and framework we need to enable this feature type.

**Comment by pandemicsyn** [comment]
FYI - created https://github.com/meltano/ext-airflow so I can start moving things out of my dev repo

**Comment by pandemicsyn** [comment]
@tayloramurphy @aaronsteers how are y'all thinking we should transition to the new extension and what do we want the migration to be like for users?

Just as a reminder, the soon-to-be old Airflow plugin was an Orchestrator, but the new extension combines Airflow, the extension, and files-airflow into a single Utility plugin. That does actually give us a bit of flexibility - since it means users could have both installed and take the new version of a spin. 

My vote would be to do a preview/beta period for a couple of weeks (at least until the sdk is settled, and we get the dbt extension done). Seem's super likely that the extension spec might still change a bit.

**Comment by tayloramurphy** [comment]
> My vote would be to do a preview/beta period for a couple of weeks (at least until the sdk is settled, and we get the dbt extension done). Seem's super likely that the extension spec might still change a bit.

@pandemicsyn strong agree. There will need to be a lot of docs update around this as well and it's not clear to me yet how we'll put this on the Hub (cc @afolson on docs concern). 

Do you have any concerns around naming? If we have an orchestrator and a utility both named `airflow` that should be okay for install, but config operations need the type flag, right?

**Comment by pandemicsyn** [comment]
> > My vote would be to do a preview/beta period for a couple of weeks (at least until the sdk is settled, and we get the dbt extension done). Seem's super likely that the extension spec might still change a bit.
> 
> @pandemicsyn strong agree. There will need to be a lot of docs update around this as well and it's not clear to me yet how we'll put this on the Hub (cc @afolson on docs concern).
> 
> Do you have any concerns around naming? If we have an orchestrator and a utility both named `airflow` that should be okay for install, but config operations need the type flag, right?

@tayloramurphy Yea, actually I was going to float that maybe to start with we call it `ext_airflow` (at least temporarily)? To alleviate any potential confusion? The naming is actually more problematic with superset since that already exists as a utility plugin with custom internal meltano handling. So using `ext_superset` there already.

**Comment by tayloramurphy** [comment]
@pandemicsyn I have a preference of a suffix, maybe `airflow_ext` or `airflow_beta`?

**Comment by pandemicsyn** [comment]
@tayloramurphy This will actually just be the name used in the meltano yaml and hub defs right? In that case, im cool with either (personally preferring the _beta suffix). 

The repos/packages themselves all use a prefix pattern, in part because that's what we have for everything else: files-airflow, tap-thing, etc is that still kosher?

**Comment by pandemicsyn** [comment]
Reopening this since we actually have two steps left:

>Docs are updated in Meltano and the Hub on how the Airflow integration is used and changed
>Hub updated to use new integration

@tayloramurphy @aaronsteers I'm gonna send a long a PR for a Hub entry (that we can keep on ice and merge when ready) but before we switch over the docs and make this "official".  Do we want to recruit some folks to test the new extension? Would also be cool to maybe try to dog-food it in the Squared project first?

**Comment by tayloramurphy** [comment]
@pnadolny13 I think it'd be worth testing this on sqaured if we have capacity

**Comment by aaronsteers** [comment]
Circling back here... @pnadolny13 - have you had a chance to test the new Airflow extension in Squared. If not, do you mind logging an issue which we can then raise for prioritization?

Thanks!

**Comment by pandemicsyn** [comment]
:shipit:  and live on hub via https://github.com/meltano/hub/pull/822 !
