### ISSUE TITLE
[Bug]: dbt metadata and files bundles point to different location for profiles

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6472]
### Meltano Version

All

### Python Version

NA

### Bug scope

Other

### Operating System

All

### Description

The metadata for some number of dbt plugins doesn't accurately represent what will be installed when the files bundle is loaded.

https://github.com/meltano/hub/blob/main/_data/meltano/transformers/dbt-bigquery/dbt-labs.yml#L20-L22 for example points to `$MELTANO_PROJECT_ROOT/transform/profiles/bigquery` but the actual file is in https://github.com/meltano/files-dbt-bigquery/tree/config-version-2/bundle/transform/profile  which is just `$MELTANO_PROJECT_ROOT/transform/profile`.

Each setting for the plugin-specific adapters should be reviewed alongside their file bundle.

This was [reported in Slack](https://meltano.slack.com/archives/C01TCRBBJD7/p1658752126724579)  by @astrojuanlu

**Comment by aaronsteers** [comment]
Hi, @cjohnhanson. Thanks for picking this up.

The correct location of the profiles directory would be the adapter-specific profile folder. So, `$MELTANO_PROJECT_ROOT/transform/profiles/bigquery` would be the correct location for bigquery. 

This is because dbt doesn't allow pointing to a specific file, and we would want to ensure conflicting profiles don't clobber or conflict with each other.

**Comment by cjohnhanson** [comment]
@aaronsteers @tayloramurphy FYI it looks like this is because the default branch for this repo was at some point changed from `master` to `config-version-2`. The path is correct in `master`, but since the pip url for the repo would just get the default branch, it's getting that incorrect version in that old branch. 

@WillDaSilva, @pandemicsyn, or @edgarrmondragon -- it looks like I don't have permissions to change the default branch in the [dbt-bigquery repo](https://github.com/meltano/files-dbt-bigquery). Do any of you have ownership of that? If so, could you either give me ownership _or_ change the default branch back to `master`? That should resolve the issue here.

**Comment by WillDaSilva** [comment]
@cjohnhanson I have updated the default branch to be `main`, which points to the same commit as `master`.

**Comment by astrojuanlu** [comment]
After the branch is changed, what would be the best way to amend the local filesystem for an existing project? (In other words: is there an alternative solution to "just delete everything and start from scratch"?)

**Comment by cjohnhanson** [comment]
@astrojuanlu unfortunately I don't think there's a simple automated solution for correcting an existing project. I think you'll need to manually change the file paths (e.g. something like `mv $MELTANO_PROJECT_ROOT/transform/profile $MELTANO_PROJECT_ROOT/transform/profiles/bigquery`).

**Comment by tayloramurphy** [comment]
`config-version-2` was introduced when dbt version 0.17.0 was launched https://docs.getdbt.com/guides/migration/versions/older%20versions/upgrading-to-0-17-0#using-config-version-2 It's not clear to me if we still need to support `config-version-1` and can just point everything to `main`. Especially considering the adapter-specific configs are mainly for 1.0 I think we're okay to just point everything at `main`. @aaronsteers anything I'm missing there?

**Comment by cjohnhanson** [comment]
@tayloramurphy FWIW all of the other adapter-specific file bundles point to `main`

**Comment by astrojuanlu** [comment]
Confirmed it works now 👍🏽
