### ISSUE TITLE
[Feature]: Collect telemetry data about how `send_anonymous_usage_stats` was configured

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6494]
The project context (and its schema) should be updated to include the key `send_anonymous_usage_stats_source` with the value `ProjectSettingService.get_with_metadata('send_anonymous_usage_stats')[1]['source'].value`, which can be one of the following strings:
- `auto`
- `config_override`
- `db`
- `default`
- `dotenv`
- `env`
- `inherited`
- `meltano_env`
- `meltano_yml`

CC @pnadolny13 @aaronsteers

**Comment by pnadolny13** [comment]
@WillDaSilva thanks for opening this. I agree that this would be useful to have.

For others reading this, the context is that we dont know where the setting comes from so sometimes we see projects toggling between opting out and opting in. We were chatting about how that could be due to different configurations in local vs production environments i.e. locally telemetry is on but in prod things are strict and its off.

From my view I dont think this is necessarily a high priority but it would be nice to know.

**Comment by WillDaSilva** [comment]
Version 1.1.0 of the project context has been uploaded to Snowcat Cloud, and put into production mode.
