### ISSUE TITLE
docs: Update "Replicate Data" docs to recommend `meltano run` instead of `meltano elt`

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6607]
https://docs.meltano.com/guide/integration still references `elt` a lot in the intro and first couple of sections. It looks like https://docs.meltano.com/guide/integration#incremental-replication-state was updated to primarily reference `run` but not the entire page.

Brought up in slack https://meltano.slack.com/archives/C01TCRBBJD7/p1660159636797759 by @visch because the outdated language made it seem like the `MELTANO_EXTRACT__LOAD_SCHEMA` variable was only available when using `elt`.

**Comment by aaronsteers** [comment]
@pnadolny13 and @visch - I do recall that we changed/removed/deprecated some of the special environment variables.

I agree we should rewrite the entire [Replicate Data](https://docs.meltano.com/guide/integration) guide to prefer `meltano run` over `meltano elt`.

1. [ ] Swap `meltano elt` references with `meltano run` wherever it makes sense to do so.
2. [ ] Anything that is specific to `meltano elt` should probably be moved to the [Advanced Topics](https://docs.meltano.com/guide/advanced-topics) page, with cross-links in appropriate section(s) of the Replicate Data page.
3. [ ] Remove the references to variables also getting passed to transformers, which is now an anti-pattern since multiple extractors and loaders can and should be able to run prior to any given transformation:
   - > the following variables describing the [extractor](https://docs.meltano.com/concepts/plugins#extractors) are available to loaders ~~and transformers~~
   - Transforms should instead seek a specific-named environment variable if they seek to be dynamic (and should always have a default value).

https://docs.meltano.com/guide/integration#pipeline-environment-variables

**Comment by visch** [comment]
@aaronsteers  My point is a bit more open which is if you search the docs for how to use `MELTANO_EXTRACT__LOAD_SCHEMA` it's not clear. You find https://docs.meltano.com/concepts/plugins#load_schema-extra which refers to `MELTANO_EXTRACT__LOAD_SCHEMA` pipeline environment variables, but doesn't' explain what pipeline environment variables are. Those are only explained in the guide.

Maybe what I"m asking for is reference material for what `pipeline environment variables` are? 

It's hard to grok as environment variables mean something to me, but we use the word all over the place

**Comment by pandemicsyn** [comment]
> We should just confirm with @pandemicsyn if all of these environment variables, or a subset, are available in `meltano run`:
> * https://docs.meltano.com/guide/integration#pipeline-environment-variables

Meltano run views pipelines slightly different, but since it uses the elt context implementation from the `elt` command, you do still get a subset of the pipeline env vars. Each extract load pair in the run invocation will see the [extractor](https://docs.meltano.com/guide/integration#extractor-variables) and [loader](https://docs.meltano.com/guide/integration#loader-variables) pipeline vars for themselves's ...but they have no idea about anything beyond themselves.

**Comment by aaronsteers** [comment]
> you do still get a subset of the pipeline env vars. Each extract load pair in the run invocation will see the [extractor](https://docs.meltano.com/guide/integration#extractor-variables) and [loader](https://docs.meltano.com/guide/integration#loader-variables) pipeline vars for themselves's ...but they have no idea about anything beyond themselves.

@pandemicsyn - To confirm, _within the EL pair_, the extractor can see the loader vars and vice versa, yes? The primary use case is the `LOAD_SCHEMA` one, tbh, since that has the critical role of allowing `tap-github` data to land in one schema and `tap-slack` to land in another schema, keeping the target's data organized without having to use plugin inheritance on the target, one target declaration for each tap.

> My point is a bit more open which is if you search the docs for how to use `MELTANO_EXTRACT__LOAD_SCHEMA` it's not clear. You find [docs.meltano.com/concepts/plugins#load_schema-extra](https://docs.meltano.com/concepts/plugins#load_schema-extra) which refers to `MELTANO_EXTRACT__LOAD_SCHEMA` pipeline environment variables, but doesn't' explain what pipeline environment variables are. Those are only explained in the guide.
> 
> Maybe what I"m asking for is reference material for what pipeline environment variables are?

@visch - Yeah, I'm definitely in favor. Reducing surface area and focusing on EL patterns specifically (and `meltano run`), I think we greatly simplify what specific use cases we would document.

**Comment by pandemicsyn** [comment]
> @pandemicsyn - To confirm, within the EL pair, the extractor can see the loader vars and vice versa, yes?

@aaronsteers yep both the extractor and loader can see all vars.

**Comment by tayloramurphy** [comment]
@sbalnojan @afolson I've put this on the DevRel board. Since the tutorial recommends `run`, we should be consistent across the documentation and only recommend `elt` as part of an advanced usage.

**Comment by pnadolny13** [comment]
Closed by https://github.com/meltano/meltano/pull/7301
