### ISSUE TITLE
spike: take an existing dbt project into a new or existing Meltano project

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6649]
**Problem:** we don't currently have a good story for how users should take an existing dbt project and bring it into their Meltano project. Do they copy and paste the files? What about their environment variables, etc.? 

**Spike**: Spend a few hours to workshop some possible paths for taking an existing, running dbt project and have it be managed by Meltano. 

Key questions that pop up immediately:

* Would we have a CLI command to import a project?
* Do we automatically install the proper component? Can we detect which one to install?
* Can we parse the profiles.yml and dbt_project.yml (or the entire project) to help with what environment variables should be set?
* Should we import any logs or other artifact data?

**Definition of done**

* We have a short write-up on the current state / experience for users - could possibly turn this into a docs page
* We have some new specific feature issues on what we could do to make this possible and easy
* We have some key questions that we'll need to answer on what we want the UX to be

**Comment by tayloramurphy** [comment]
@aaronsteers I'll bring this one to our next sync meeting.

**Comment by pnadolny13** [comment]
@tayloramurphy I spiked on this using the [jaffle shop](https://github.com/dbt-labs/jaffle_shop) project as an example to clone. Some thoughts:

1. Steps 4 and 5 below are the cloning/merging process thats the tricky part. We need to clone the repo and copy the existing dbt artifacts into the meltano dbt structure. The things I dont think we want to overwrite are the `.gitignore` and `dbt_project.yml` files. Maybe a smarter script or CLI command can move  everything except those? 
2. We put seed files in the `data` directory whereas the jaffle project put them in `seeds`, and plenty of people probably do something different. We'd need to either simply document where we expect everything to be and ask the user to put them there or move their existing directories in then ask them to update the dbt_projects.yml to reflect the accurate directory. If they call the seeds folder `foo_bar`, I guess we could compare their original dbt_projects.yml and either update ours or write their data to the appropriate meltano conforming directories.
3. Merging our dbt_project.yml looks like it can probably be done automatically. I only see our `target-path`, `profile`, and `clean-targets` entries needing to change. Or start with ours and ask them to copy in their models/seeds/snapshots configs (I did that in my test script below). The challenge is that if any of those things change in the file bundle then our migration steps will need to change too. I wonder if its better to always accept our file bundle as the starting place and bring their stuff in from their.

Key Questions:
- do we want to try to be smart and diff their dbt_projects.yml or document it and have them do it?
- if we do diff their dbt_projects.yml do we rename their directories to match meltano or update meltano's default structure to match their existing directories (least change is probably preferred by them)?

My script:

```sh
# 1.) Turn on Postgres Docker
docker run --rm --name postgres -e POSTGRES_PASSWORD=meltano -e POSTGRES_USER=meltano -e POSTGRES_DB=warehouse -d -p 5432:5432 postgres

# 2.) Create Meltano Project
export MELTANO_SEND_ANONYMOUS_USAGE_STATS=False
meltano init dbt-migration
cd dbt-migration

git init
git add --all
git commit -m "meltano init"

# 3.) Add dbt-postgres
meltano add transformer dbt-postgres
meltano config dbt-postgres set host localhost
meltano config dbt-postgres set user meltano
meltano config dbt-postgres set password meltano
meltano config dbt-postgres set port 5432
meltano config dbt-postgres set dbname warehouse
meltano config dbt-postgres set schema analytics

meltano invoke dbt-postgres debug

git add --all
git commit -m "add dbt-postgres"

# 4.) Clone external dbt repo and move all folders. Ignore .gitignore and dbt_project.yml explicitly
cd transform
mkdir repo_clone
cd repo_clone
git clone https://github.com/dbt-labs/jaffle_shop.git
cd ..

mv repo_clone/jaffle_shop/models/** models/
mkdir etc && mv repo_clone/jaffle_shop/etc/** etc/
mkdir data && mv repo_clone/jaffle_shop/seeds/** data/
mv repo_clone/jaffle_shop/README.md README.md
mv repo_clone/jaffle_shop/LICENSE LICENSE

# Note: Update seeds directory to data or update meltano's dbt_project.yml
    # data
    # models
    # analysis
    # tests
    # macros
    # snapshots

# 5.) Manually move `model` setting from your dbt_project.yml to meltano dbt_project.yml

# 6.) Clean up
rm -rf repo_clone

meltano invoke dbt-postgres debug

git add --all
git commit -m "migrate dbt project to meltano"


# 7.) Run jaffle shop via Meltano

meltano run dbt-postgres:seed dbt-postgres:run dbt-postgres:test dbt-postgres:docs-generate dbt-postgres:docs-serve

# References
# https://hub.meltano.com/transformers/dbt-postgres
# https://docs.meltano.com/getting-started.html#transform-loaded-data-for-analysis
# https://github.com/dbt-labs/jaffle_shop
```

**Comment by tayloramurphy** [comment]
@pnadolny13 this is really great. Thank you for taking the time on this. 

From our end, I think we could have a fairly simple first iteration that wouldn't even require any new meltano features. Similar to what lightdash is doing, I bet we could write a shell script that users could run to do an import of their existing project. I'm not sure where this would live exactly, but I'm imagining it could:

* accept a git URL or local directory that has a dbt project
* parse the profiles.yml to get the target (and possible recommend additional environments! we could also parse the Jinja to see what `env_var` they need to set)
* auto-install the proper adapter plugin
* fully replace what's in the file bundle (possibly merge .gitignore but maybe nothing else)
* prompt them to enter their credentials. 

> do we want to try to be smart and diff their dbt_projects.yml or document it and have them do it?

First pass - probably not. I think we could merge the .gitignore but have them do everything else.

> if we do diff their dbt_projects.yml do we rename their directories to match meltano or update meltano's default structure to match their existing directories (least change is probably preferred by them)?

I think we could replace everything inside of `/transform`. An assumption is that this is version controlled, so it should all show up in the diff

> how do we manage config version changes? If we had a CLI command, would we need to have compatiability ranges between meltano, file bundles, and dbt config files?

Perhaps this is part of the `dbt-ext` that @pandemicsyn is working on? I'm not sure, but for a first test / iteration we could just say "requires latest version(s)".

**Comment by aaronsteers** [comment]
@tayloramurphy - I'd take a slightly different take on this.

1. Install their adapter-specific dbt plugin in the normal way (`meltano add transformer dbt-snowflake`, for instance) with out-of-box settings.
2. Set creds and auth using `meltano config set` or (soon) `meltano config set --interactive`.
3. Merge the the two `dbt_project.yml` files by copying in the contents of their old file, and removing duplicate entries.
4. XCopy transformations into `transforms` (or really any directory they want).
5. Merge their own settings (excluding creds and auth) from their `profiles.yml` into `/transforms/profiles/snowflake/profiles.yml`.

**Comment by pandemicsyn** [comment]
> Perhaps this is part of the dbt-ext that @pandemicsyn is working on? I'm not sure, but for a first test / iteration we could just say "requires latest version(s)".

@tayloramurphy I - don't *think* it will be - and guessing the "requires latest" is what I'd opt for. But I haven't started on dbt yet. My game plan was going to be a lot like Airflow/Superset - where its basically just a minimal implementation that matches what we have today, or improves on what we have - when its obvious to me. 

Beyond that, I'm definitely going to need some guidance/help on what we want to do on the dbt side. If we ever do the dog fooding projects I might get more exposure to dbt, but as is - I can still count the number of times I've used dbt on two hands. Just mentioning that because, y'all have history with dbt that makes it easy to see the gaps in the current integration. 

But I don't have that, and that makes it really hard for me to even guess at what kind of improvements we should build in. Like, there's definitely an implied "florian does a research spike to finally figure out how dbt works without meltano" at the start of the dbt extension work.

So, if y'all are expecting additional awesome-sauce during the initial port to the extension or that's worth keeping in mind during the initial build I'd definitely say, please go document it on https://github.com/meltano/meltano/issues/6434.

**Comment by pnadolny13** [comment]
>parse the profiles.yml to get the target (and possible recommend additional environments! we could also parse the Jinja to see what env_var they need to set)

@tayloramurphy I was actually assuming that we'd leave the default meltano profiles.yml since it pre-configures dev/stage/prod targets that work using meltano environments. Usually dbt targets are used to toggle between environments so my understanding was that our profile should eliminate the need for users to mess with that. Basically dbt is deferring its environment management up to meltano. In that case we'd want to recommend our default over whatever they've previously configured. Right?

Its really a question of whether we want to reconfigure their project slightly to conform with the meltano default/recommendations or if we want to make as few changes as possible to match their existing project as closely as possible. 

>Ideally there'd be a connectivity test they could run after this stage: meltano run dbt-snowflake:test

@aaronsteers there is! I found this in the jaffle shop project but `meltano invoke dbt-postgres debug` makes sure you have a valid dbt_project.yml/profiles.yml, prints your current connection settings, and does a connection test. So in my little script above I ran it after installing/configuring dbt-postgres and then again after I finished merging the projects.

The more I think about this the more I like the idea of just documenting this process well. Its probably a worse experience to use some black box command to merge the two vs us having details docs with a step by step showing how to bring your project in and explaining the trade offs of different ways to merge (i.e. you can keep your existing targets but if you conform to ours then meltano environments works out of the box).

**Comment by tayloramurphy** [comment]
> The more I think about this the more I like the idea of just documenting this process well.

I think that's probably right (and rereading my original definition of done I realize I was already at that conclusion). 

@pnadolny13 when you come back from vacation would you make a pass at a short write-up on this?

**Comment by pnadolny13** [comment]
I created https://github.com/meltano/meltano/issues/6704 to track that documentation work and assigned it to myself to do soon. I also created https://github.com/meltano/meltano/issues/6705 to optionally add automation around it so we dont lose track of it, I'll leave that in the backlog for you to decide on based on priority.

Closing this out.
