### ISSUE TITLE
Meltano Run - Introduce support to select dbt models directly in query

### ISSUE THREAD

**Issue by SBurwash** [meltano/meltano#6810]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Good day,

I'm trying to run an end-to-end ELT process through meltano, starting with loading and extraction, and then updating my models with dbt.

Currently, my process looks like this: 
`
meltano run my_custom job
`
where `my_custom_job` looks like this:
```
- name: my_custom_job
  tasks:
  - tap-foo target-bar
  - dbt-bigquery:run-select-foo
```
where `run-select-foo` is a custom dbt command which looks like this: `run --select foo+`

Would it be possible to bypass the custom command and simply write my job like this:
```
- name: my_custom_job
  tasks:
  - tap-foo target-bar
  - dbt-bigquery invoke:run --select foo+
```

This could possibly be assured by adding a recognizeable flag in front of the task such as 
```
- name: my_custom_job
  tasks:
  - tap-foo target-bar
  - [DBT] dbt-bigquery invoke:run --select foo+
```

Thanks!

**Comment by tayloramurphy** [comment]
@SBurwash you should be able to do 

```yaml
- name: my_custom_job
  tasks:
  - tap-foo target-bar
  - dbt-bigquery:run-select-foo
```

to reference the custom command. 

Would that do what you're looking for? The job definition wouldn't be expecting command line arg input like that, though I think we've talked about it in the past.

**Comment by SBurwash** [comment]
Yes we have broached on the subject before, but as our dbt stack is growing and I want to implement tests **before** syncing, this is becoming a larger value feature for me

**Comment by tayloramurphy** [comment]
@SBurwash the first thing that comes to mind is to reference an environment variable that you would then use in your `--select` in the command. 

So `run --select $MY_VAR` and then either export what you want prior to running or have it in the `env` key of the schedule. 

I am curious though what "Would it be possible to bypass the custom command and simply write my job like this" would actually get you that's helpful though? Is it primarily about being able to define the command at the schedule level and not the plugin level?

**Comment by pnadolny13** [comment]
@tayloramurphy I'm not sure this is exactly what @SBurwash is running into but I think I feel similar pain in the squared project. In order to run a subset of dbt models as part of a schedule I need to:

1. [Define it as a dbt command](https://github.com/meltano/squared/blob/b6a126639b8c8b39f4549a5741a9245bd2c5f6bf/data/transform/transformers.meltano.yml#L13)
1. [Reference it in a task list of a job](https://github.com/meltano/squared/blob/b6a126639b8c8b39f4549a5741a9245bd2c5f6bf/data/orchestrate/orchestrators.meltano.yml#L122)
1. [Assign it as the job thats part of the schedule](https://github.com/meltano/squared/blob/b6a126639b8c8b39f4549a5741a9245bd2c5f6bf/data/orchestrate/orchestrators.meltano.yml#L51)

It is a bit redundant. I could see it being valuable to skip step 1 in favor of directly including the select criteria in the task list of a job, aka step 2.

Does that make sense?

**Comment by tayloramurphy** [comment]
@SBurwash we don't currently support the `env` in jobs - but I'm open to it! 

* https://github.com/meltano/meltano/issues/6386 is an issue previously opened on that

**Comment by WillDaSilva** [comment]
Still relevant
