### ISSUE TITLE
Add context and/or a help link to "Environment not found" error

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6832]
We could create something like http://melta.no#environment-not-found when folks run into

- #6677 

We could also give hints such as using the `--no-environment` flag or running `meltano environment add dev`.

This could leverage the new `MeltanoError` class and practices.

**Comment by WillDaSilva** [comment]
@aaronsteers This may not be necessary after the following two PRs:
- #6877 
- #6862

The new error messages from #6862 are fairly clear, and #6877 will make it so that when the user does not have `default_environment` set in their `meltano.yml`, they won't be told that the `dev` environment (which they never made or asked for) cannot be found.
