### ISSUE TITLE
Feature proposal: meltano-manifest.json

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6876]
Related to:

- https://github.com/meltano/meltano/discussions/6944
- https://github.com/meltano/meltano/discussions/6766

As discussed in office hours on 2022-10-12.

Feature goals/requirements:

1. Stability. Since this would serve as the base for many interop/integration scenarios, we want to make the format as stable as possible.
2. Self-contained. There should be no need to reference external files or services when using this format. So, for example, lock file content would be embedded so no external references are needed.
3. Pre-calculated inheritance, precedence, and override effects. The reader shouldn't need to know how inheritance works, or understand any other internal Meltano business logic.
4. No secrets. This artifact essentially needs to be treated as 'code' and may be passed around in less-trusted contexts. As such, it should _not_ contain: env vars from local OS or terminal context, env vars from `.dotenv`, settings values from `systemdb` or other external settings/secrets providers.
5. Simple as possible. Bonus points if the new json manifest is able to be validated against existing JSON Schema rulesets, without creating or maintaining net new data structures.

So, given these guidelines, here's a possible path forward:

1. Start with contents and structure of the `meltano.yml` file itself.
2. Merge in all data from `include_paths` declarations.
3. Super-populate each plugin definition in the global context:
   1. Inject all properties from the lock file, except of course, those properties overridden.
   2. Calculate the value of each entry of the plugin's `config`.
   3. Optionally, we can store 'extra' info about how the evaluation was performed under a `meta` or `vendor` key that is explicitly non-stable or at least explicitly free-form.
   4. Environment variable declarations in plugin config should be left unresolved until runtime. If we are confident that the value can be resolved without leaking any sensitive info, the predicted evaluation could optionally be rendered under a `meta` or `vendor` key, without losing fidelity of the config's env var reference.
5. Repeat the above process for each declared Meltano Environment.
6. Inject other top-level entities (`jobs`, `env`, `schedules`, etc.) into the environment declarations if applicable, so that each environment definition is standalone. 

Variations:

1. We optionally could give an environment name to the 'global' or `--no-environment` behavior, so that the top-level file is just the environments declaration: `version: 1 \n environments: [...] \n <EOF>`. This reduces the clutter in the file, and readers would only deserialize the environment definition they need in the given context.
2. We could optionally create separate manifest files per environment so that the manifest is specific to what is needed exactly in a given context.

**Comment by pnadolny13** [comment]
A use case we discussed in office hours:

In squared we [generate a json file](https://github.com/meltano/squared/blob/a90c111731c28c11c50111bc162a1d67d1221f71/.github/workflows/prod_deploy.yml#L29) with the schedule list output, during CI deployment of our docker files.

The [DAG generator prefers the cache](https://github.com/meltano/squared/blob/a90c111731c28c11c50111bc162a1d67d1221f71/data/orchestrate/dags/meltano.py#L212) if it exists over repeatedly running `schedule list` so in production we dont run meltano in airflow containers. Its a static read only environment anyways so no need to refresh.

**Comment by WillDaSilva** [comment]
Timestamped recording of the office hour discussion: https://www.youtube.com/watch?v=0wzaXR5dofU&t=1404

**Comment by kgpayne** [comment]
Also relevant for generating documentation, e.g. [`sphinx-meltano`](https://github.com/MeltanoLabs/sphinx-meltano). Ideally the manifest would include full definitions and descriptions of plugins/settings for rendering in html (as at the time of manifest generation).

**Comment by JulesHuisman** [comment]
This would also be great for the dagster extention. If it is possible to also include the (selected) schema of the extractors this would allow me to more easily create Software Defined Assets for the taps.

Let me know if there is anything I can contribute to!

**Comment by aaronsteers** [comment]
@JulesHuisman, @kgpayne, @WillDaSilva, @pnadolny13 - I've updated the description above with a proposed implementation spec and some broad goals/principals that I thought would be helpful for discussion.

@JulesHuisman - This does not as of now include any scope for the schema of the extractors. Do you think it's okay to postpone this for a first edition? I imagine a path forward for schema may become clearer after we have something like the proposed [meltano catalog](https://github.com/meltano/meltano/discussions/6766) feature.

**Comment by JulesHuisman** [comment]
@aaronsteers I can clarify our use case a bit more, this might help with further designing the manifest / catalog features. 

For the Dagster extension we need to read both the Meltano jobs and schedules. This results in the fact that we need to run `meltano job list --format=json` and `meltano schedule list --format=json`. As invoking Meltano can be a bit slow, some async magic needs to be added to limit the time to get this information. Ideally this information could be gathered using one single command (or from one single file). If I'm interpreting it correctly this would be part of the Meltano manifest? 

Furthermore, we want to read the (selected) schemas of the taps (or ideally the schema that arrives at the target, in case of mapping). As this allows us to, by combining with `dagster-dbt`, to automatically infer all your data assets (using Dagster's Software Defined Assets). Creating a really tight integration with Dbt. In an ideal world this information could also be extracted from the manifest file, as this makes it really easy for extensions to do some sort of introspection on the Meltano project itself. This would be comparable to how dbt creates its manifest.

From the dbt docs:
> This single file contains a full representation of your dbt project's resources (models, tests, macros, etc) ...

> This does not as of now include any scope for the schema of the extractors. Do you think it's okay to postpone this for a first edition?

Makes perfect sense. Inferring the schemas of the extractors is the missing piece from creating all the Dagster assets, so I am excited to see a feature like this, one way or another.

**Comment by aaronsteers** [comment]
@JulesHuisman - re:

> For the Dagster extension we need to read both the Meltano jobs and schedules. ... If I'm interpreting it correctly this would be part of the Meltano manifest?

Yes, 100%.

> Furthermore, we want to read the (selected) schemas of the taps (or ideally the schema that arrives at the target, in case of mapping). As this allows us to, by combining with `dagster-dbt`, to automatically infer all your data assets (using Dagster's Software Defined Assets). Creating a really tight integration with Dbt. In an ideal world this information could also be extracted from the manifest file, as this makes it really easy for extensions to do some sort of introspection on the Meltano project itself. This would be comparable to how dbt creates its manifest.

Completely understood in terms of the use case here.

> > Do you think it's okay to postpone this for a first edition?
> 
> Makes perfect sense. Inferring the schemas of the extractors is the missing piece from creating all the Dagster assets, so I am excited to see a feature like this, one way or another.

While I'm hesitant to include catalog features in the manifest file before we've spec'd out `meltano catalog` as a feature, a compromise we could offer is to optimistically scan for any pre-cached catalog elements and include the json from those files under a `meta` or `vendor` tag. By putting this less-stable part of the content under a `meta` key or similar, we declare the they are not formally a 'stable' part of the spec, and future versions could (and probably would) break the initial behavior assumptions.

Also, for any taps that don't support discovery, or for taps that haven't yet had their catalogs cached, that entry would be missing. (When orchestrating directly, the user can mitigate this by forcing all taps to run discovery ahead of exporting/shipping their manifests.)

What do you think about this as a possible compromise?

**Comment by JulesHuisman** [comment]
@aaronsteers 

> What do you think about this as a possible compromise?

Yes, a solution like this would work. The assets part of the dagster extension would also be a work in progress, so that should be fine!

> Edit: I realized after writing the above that a potential risk of including the catalog at this phase is that the inclusion of Singer catalog content could blow up the file size exponentially. Still doable, but probably something we'd want to be able to toggle on/off in cases where the extra bloat is not desireable and the catalog metadata is not directly needed for the intended application.

How would the manifest be generated? Would it happen automatically when running certain commands, or would there be a specific command like `meltano manifest generate`? If it's the latter, maybe there could be some kind of opt-in flag, like: `meltano manifest generate --include-catalog`.

**Comment by aaronsteers** [comment]
> @aaronsteers 
> 
> > What do you think about this as a possible compromise?
> 
> Yes, a solution like this would work. The assets part of the dagster extension would also be a work in progress, so that should be fine!

👍👍


> > Edit: I realized after writing the above that a potential risk of including the catalog at this phase is that the inclusion of Singer catalog content could blow up the file size exponentially. Still doable, but probably something we'd want to be able to toggle on/off in cases where the extra bloat is not desireable and the catalog metadata is not directly needed for the intended application.
> 
> How would the manifest be generated? Would it happen automatically when running certain commands, or would there be a specific command like `meltano manifest generate`? 

Probably both methods - automatic and on-demand. 



> If it's the latter, maybe there could be some kind of opt-in flag, like: `meltano manifest generate --include-catalog`.

Yeah, I think something like that could definitely work.

**Comment by aaronsteers** [comment]
@JulesHuisman - Out of curiosity, how much metadata does Dagster leverage? Does it use the top-level column list, data types, and/or subproperties when applicable?

**Comment by JulesHuisman** [comment]
> @JulesHuisman - Out of curiosity, how much metadata does Dagster leverage? Does it use the top-level column list, data types, and/or subproperties when applicable?

@aaronsteers To make the Dagster assets work, I would only need the stream names of the taps. For example, here you can see the comments, commits and projects streams.

![image](https://user-images.githubusercontent.com/26525996/195979482-0bf51ab9-b285-4bbf-ba76-93dd6bb56db0.png)

However, if you want (this is not required) you can also add all kinds of other metadata to each asset. Here is an example from the `dagster-airbyte` integration:

![image](https://user-images.githubusercontent.com/26525996/195979607-6f3eb883-118d-451e-8983-555782301b68.png)

Where the schema of the data is also added.

**Comment by aaronsteers** [comment]
@JulesHuisman - From the above, it looks like we'd ideally just capture the whole _selected_ part of the JSON schema per stream. Assuming we just use `schema` as the property name for the JSON schema definition, and assuming we drop from the schema everything that has been deselected by the user, the spec starts to take shape here pretty organically...

_Note: I'm including psuedocode below in yaml for ease of typing and readability. The actual manifest would list would be json - to distinguish between user-editable resources (that prefer yaml) vs pure machine-readable artifacts for interop (for which we generally would use json)._

```yml
plugins:
  extractors:
    tap-github:
      pip_url: ...
      # ...
      select:
      - repositories.*
      - "!*.reactions"
      - # ...
      streams:
      # A very simplified pre-resolved version of the upstream schema
      # for each of the extractor's streams
      - name: repositories
        key_properties: [...]
        replication_key: null
        schema: {...} # json schema here
      # ...
```

We already have another function using the key `catalog` at this level (used for catalog overrides today), but perhaps a `streams` key could work (instead of hiding under an interim `meta`/`vendor` key). The JSON Schema is pretty non-controversial in terms of compatibility with our own Meltano/Singer paradigms and interop with other platforms - especially if we pre-filter it, since that removes the requirement for needing `metadata` and other Singer-specific catalog details. The primary keys and incremental replication key values would probably would be worth including as well.

Still worth calling out that the inclusion of a `streams` entry presupposes that _either_ we've already ran discovery on the extractors, _or_ that we have built the future `meltano catalog` feature which would store those in a long-term git artifact other than the local `.meltano` cache files.

Assuming that discovery has run and we already have a catalog cache, this is not a lot more surface area to add. And the fact that we would be excluding deselected streams makes me less worried about file sizes overall.

**Comment by tayloramurphy** [comment]
@aaronsteers I put this in Iteration 27 based on our Alpha needs.

**Comment by aaronsteers** [comment]
@WillDaSilva - As you pick this up, I just want to summarize a couple expectations here.

## CLI

The top-level description text in the main body of the `meltano compile` UX spec is up-to-date [here](https://github.com/meltano/meltano/discussions/6944). (Individual discussion threads might not be though.)

## Data structure

Data structure. Even though we're creating a brand new file here to handle a new set of use cases, I would very much like to avoid creating a net new file format to the extent we can avoid it. This is to eliminate causes of failure and costly translation efforts.

Said another way, I would love to see this as a merge and adaptation of JSON Schemas from the plugin lock files and meltano.yml itself - but ideally not creating many/any new data structures that would need to be maintained separately from Meltano's already existing data structures.

As an example, anything that is legal in a plugin's lock file should probably be legal to be overlayed onto the plugin definition itself in the manifest. If we add or deprecate a field in the `plugin` object definitions, we'd like this to pass through to the manifest without having a second set of changes to make.

As much as possible, I'd like the first iteration to just be a passthrough of existing data elements and data structures. This is to minimize maintenance surface area. 

A V2 could try to simplify or standardize inputs - but with those changes would come many more conversations around long-term spec needs that we don't want to creep into our scope here. (Renaming `env:` to `env_vars:` for instance, or deprecating `variant` and replacing with `maintainer_id`.)

## Security and Deferred Env Var Resolution

I think we should _not_ resolve env vars or access any remote settings stores when resolving the manifest. Meaning, anything set in the `systemdb`, the terminal env var context, or in `.env` would be unknown and unresolved from the perspective of the manifest file. This is because manifest file must be deployable to environments that have their own secrets access (or not, which would rightfully cause them to fail) and would have their own ability to override or inject their own env var contexts at runtime.

For example, a `pip_url` that contains a env var reference will remain unresolved in the manifest - which means the manifest itself does not need to be treated as a secret. The manifest would have the same sensitivity level of the git-committed resources: contents may be proprietary and contain potentially confidential IP, but they don't contain credentials or other secrets that would compromise connected users and systems.

## Catalog excluded for now

While I think it's worthwhile to have catalog artifacts included over the long run, we're just not ready with the data spec as of yet - and it will introduce undesirable complexity and volatility in the first iteration.

**Comment by WillDaSilva** [comment]
@aaronsteers Thanks for the summary. One question for now: when compiling the manifest for a single environment, do we keep the structure the same as with the all-environment manifest (i.e. the single environment is found under the `environments` key, and the top-level "global" elements are present as normal), or do we pull the environment up into the top-level of the manifest, and exclude the environments key?

I'm leading towards the latter because it makes for a simpler environment-specific manifest. Once you've chosen to read e.g. `meltano-prod-manifest.json`  you shouldn't have to know whether you need to read `.plugins` or `.environments[0].plugins` - you've already made your choice to get information specific to the environment.

**Comment by aaronsteers** [comment]
> I'm leading towards the latter [pull the environment up into the top-level of the manifest, and exclude the environments key] because it makes for a simpler environment-specific manifest

I agree! Yeah, sounds like a good plan. This removes ambiguity from the user of the file - they can take the assumption that they have the file corresponding to their environment, and just run with it.

**Comment by aaronsteers** [comment]
> Once you've chosen to read e.g. `meltano-prod-manifest.json` you shouldn't have to know whether you need to read `.plugins` or `.environments[0].plugins` - you've already made your choice to get information specific to the environment.

💯 

I think there may be an argument here for in the 'full file' to also just _not_ have anything that isn't wrapped under `environments` collection. Anything at `.plugins` should be redundant with what we injected to `.environments[0].plugins`, and can therefor be removed to avoid ambiguity for the receiver. Then, every environment declaration is truly isolated from the others, with no unresolved or 'which should I use' questions left to those consuming.

**Comment by WillDaSilva** [comment]
I am trying to use the `meltano.yml` schema to determine which objects can have an `env` object as a child, but I am struggling to include the schema in the wheel.

If I add it to the Poetry include paths, it is included, but not as part of the Meltano package.

If I use a symlink then Poetry errors while building the wheel.

We could move the schemas into `src/meltano/schema`, but then we'd have to update their location in https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json, and I'm not a fan of having them under `src/meltano/` anyway (though I suppose it makes some amount of sense if we're using them to influence behaviour at runtime for a particular installed version of Meltano).

Perhaps `build.py` would work, but I'd rather avoid relying on it any more than we have to. That's what I'll try next.

**Comment by WillDaSilva** [comment]
@aaronsteers @tayloramurphy In order to have a relatively flat manifest wherein you don't have to perform computations on the config at runtime, while still making it compatible with the Meltano project file schema, we'll need to have more than just one manifest file per environment as suggested above.

This is because schedules currently have `env` blocks, and jobs likely will in the future too. We may also want to support plugin config at these levels in the future too.

To have a fully pre-computed manifest file we have to make each leaf node in the project files (i.e. contexts in which Meltano can actually do work) static. It can't change based on whether you're calling from one environment or another, or running under a schedule or not, or running a job or not. To accomplish this for environments we agreed that we'd create a separate environment for each manifest file, but at the time I didn't realize that we actually need one for each combination of these 3 contexts in which Meltano can be running. If I'm missing any other such execution contexts, we'll need to incorporate that in the same way.

To handle this, I propose we decide on an arbitrary order for these contexts, such as `(environment, schedule, job)`, then create each manifest file for a particular combination of them in that order. These can determine the file name of each manifest file: `meltano-manifest.<environment name>.<schedule name>.<job name>.json`. This may be an issue if `.` is a legal character within any of these names, so we may have to hash each of the names to avoid that problem.

This is just the default name/location for a manifest file - when one is generated manually via `meltano compile` the `--output` parameter can be used to save the file to a different location, e.g. `--output ./manifest.json`. Specifying `--output` should only work if a single manifest file is being generated. If some context (e.g. the schedule) is left unspecified, then an `--output-dir` must be specified instead in which manifests for every value of the unspecified context will be generated.

Each context has a global/none option, so you end up with `(e+1)(s+1)(j+1)` manifest files, where `e` is the number of environments, `s` is the number of schedules, and `j` is the number of jobs.

If we compile them only as-needed and selectively, that's fine.

As-needed in the case where you're some part of `meltano.core` and you want to get config for whaterver you're doing now, so you request a manifest for the current environment-schedule-job triple. If it already exists for the current hash of the project files (maybe that hash can be stored within annotations?) then it's simply read.

Otherwise a new manifest is generated, and saved to disk. Selectively when you're operating outside of a Meltano process and need data about a project. You run `meltano compile --environment <environment name> --schedule <schedule name> --job <job name>` instead of `meltano compile`, and thereby only generate the manifest for the desired triple.

If it really is the case that all combinations are needed... oof. Hopefully we can generate them quickly, and the project files don't have too many environments/schedules/jobs.

**Comment by WillDaSilva** [comment]
On second thought, my proposal above suffers from an issue: each manifest file would have `environments`, `schedules`, and `jobs` lists that have only 0 or 1 entries. You wouldn't be able to get info about e.g. all schedules for a given Meltano project without generating/reading many manifest files, which is pretty clunky.

That same problem exists with environments in the prior proposal.

I'm not sure how to both create fully pre-computed files, and represent all of the info about a Meltano project one may want. Abandoning the Meltano project files schema may help. We may be able to make use of a dangerously large amount of nesting within a single-file manifest by putting every possible combination of the aforementioned context triples within it. For example, under each of the `schedules` list items would be the rest of a Manifest file, but with the `schedules` field removed. Likewise one could descend from there into one of the listed `environments`, and find the rest of a Manifest file nested within it, but now lacking both the `schedules` and `environments`.

This approach manages to represent all info about a Meltano project in a single pre-computed file, but suffers even more from combinatorial explosion because we no longer enforce an order for the elements of the context triples. Where the previous approach takes $(e+1)(s+1)(j+1)$ compilation steps, this new one takes 6 times that. In general, it takes $n!$ times as long as the previous approach, where $n$ is the number of contexts we need to account for. If we define $a_i$ as the number of elements in the $i^{th}$ context, then the number of compilation operations necessary to compute this full manifest is:

$$n!\prod^{n}_{i=0} (a_i+1)$$

We can't compute this on-demand or partially as we could with the prior approach, so this "solution" really just trades one problem for another.

**Comment by WillDaSilva** [comment]
Maybe the only viable approach is a hybrid, wherein we have multiple manifest files of the form `meltano-manifest.<environment name>.<schedule name>.<job name>.json`, which don't contain general information about e.g. what all the schedules are, or what all the environments are, etc., but then we also have manifest files of the form `meltano-manifest.json` which contains all non-ambiguous information when no context is specified, or `meltano-manifest.<environment name>.json` which contains all non-ambiguous information when an environment is specified, but no schedule or job is specified.

Ambiguous information would be anything the missing contexts could affect, which at least includes env vars for all higher levels, but also may include plugin configs in the case of unspecified Meltano environments.

Obviously the manifest filepath scheme would need to be reworked somehow.

This would enable the necessary performance benefits explained in [this comment](https://github.com/meltano/meltano/issues/6876#issuecomment-1362384769) below "If we compile them only as-needed and selectively, that's fine", while still providing a method by which one can get general high-level information about a Meltano project without specifying a specific execution context, such as a list of all of the schedule names and their intervals.

The main problem with this hybrid approach is that it is the most complex for the consumer of this data, compared to the other two approaches discussed here. Still significantly easier than correctly processing a `meltano.yml` file, however.

**Comment by aaronsteers** [comment]
@WillDaSilva - I hear the inherent conflict in trying to _fully_ resolve all references and still have a viable resolved config set for all combinations.

What if we relax the requirement that schedules are jobs have _fully_ resolved definitions and just allow that a meaningful execution of the file would still require overlaying any job-specific or schedule-specific overrides?

Also worth noting that while jobs should always be orthogonal to environments (meaning all jobs in theory should be runnable on any environment), schedules will soon have their own environment affinities. 

I think it's ok to leave both jobs and schedules in a more or less unchanged from source material when storing in the manifest. There are some good reasons to do this, since an orchestrator that wants to invoke jobs or schedule jobs _should not_ get lost in the details of internal plugin details and config paths. The orchestrator just needs to know how to call Meltano and what overrides (if any) to send to Meltano. Then, Meltano will handle the job of overlaying whatever env vars exist in the is.environ context (for instance) and how those sound interact (or not) with the called plugins and commands.

Would this work and does this help keep things simple?



 orchestrator would then need to understand

So, we'd try to resolve each environment

**Comment by cjohnhanson** [comment]
We had a really productive synchronous discussion on this during codeshare today, which I'm summarizing here.

The conclusion we came to was that there is a core conflict in how we want to resolve environment variables in Meltano vs. how we would _need_ to resolve environment variables to persist to a hierarchical data format like JSON with all possible invocation environments fully resolved.

For meltano, the different "nodes" where environment variables are resolved is a directed graph, but not a tree. At any given "node", the resolution of environment variables is dependent on the path taken to arrive at that node. E.g., a plugin's invocation environment can be inherited directly from a meltano environment (like `dev`) during `meltano invoke`;  it can be inherited from a job (which inherits from a meltano environment) during `meltano run <job name>`; it can be inherited from a schedule (which will soon inherit from an environment) during `meltano schedule run` if the schedule defines a set of plugins directly; or it can be inherited from a job (which inherits from a schedule, which inherits from a meltano environment) during `meltano schedule run` if the schedule references a job.

For meltano core and meltano cloud, this is workable since the logic is within meltano itself in the case of the former and in the case of the latter, we can iterate on the logic as needed without breaking any contracts/compatibility that consumers depend on -- we're the only consumer. 

For other consumers of a meltano manifest, this is problematic since we want to provide the manifest in a widely-used hierarchical format like JSON. So would need to either significantly change things on the meltano core side to make environment variable resolution a strict tree that we can serialize into a hierarchical format _or_ force consumers of the meltano manifest to implement (or possibly import via a separate small package/utility that we maintain, or by requiring them to use meltano core to read the manifest) the logic required to fully resolve the environment at every possible node, either by not resolving them at "compile" time and compiling to a hierarchical format like JSON with some env vars not resolved, or by compiling to a graph serialization format that is capable of representing the actual data. We quickly dismissed the former option but the latter option obviously conflicts slightly with the intended purpose of the meltano manifest.

**Comment by WillDaSilva** [comment]
@cjohnhanson Thank you for the accurate summary, and the good ideas/discussion during the codeshare call.

@aaronsteers What you suggest seems pragmatic, and doable. The catch with that approach is that it limits what we can have as the env var precedence. @tayloramurphy [says that the following is ideal](https://meltano.slack.com/archives/CKHP6G5V4/p1671721910934249?thread_ts=1671678255.042419&cid=CKHP6G5V4):

```
- environment level plugin env # highest
- schedule level env
- job level env
- root level plugin env 
- environment level env 
- root level env
- .env file
- terminal env # lowest
```

If we have one manifest file per environment, then the precedence may only have the schedule env and job env below the lowest level that the manifest compiler pre-expands:

```
- environment level plugin env # highest
- root level plugin env 
- environment level env 
- root level env # everything at or above this is pre-expanded by the Manifest compiler; everything below may be "hydrated" into it at runtime
- schedule level env
- job level env
- .env file
- terminal env # lowest
```

If this limitation is acceptable, then that gives us a path forward. If we are not comfortable with this limitation, then I can explore the idea that @cjohnhanson and I discussed in the codeshare call where the manifest would be a graph, and the expansions would be computed based on which path along the edges were taken to reach a particular vertex. Or more realistically, we can wait until we've had an opportunity to discuss this synchronously with more people, and come to a better solution.
