### ISSUE TITLE
Feature: `meltano state sync` to replicate bookmarks from one backend to another backend

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6953]
Would be a follow on to:

- #6911 

This would basically the equivalent of `meltano state copy` but copying the content from multiple `state_id`s from one backend to another.

Examples, for discussion purposes:

```console
# Copy all bookmarks from systemdb to the designated S3 backend URI
meltano state sync --from_backend=systemdb --to_backend=s3://my-bucket/my/root/path/

# Copy bookmarks with a `prod:` prefix from systemdb to the designated S3 backend URI
meltano state sync --pattern='prod:*' --from_backend=systemdb --to_backend=s3://my-bucket/my/root/path/
```

**Comment by qbatten** [comment]
A related feature that would be really helpful for my test/dev setup is a `meltano state dump` command that just dumps all existing state. Not *that* hard to do that manually but a single command would be super convenient.

Another way to get that same functionality would be if `meltano state get` accepted a pattern and returned all matching state_ids. That seems like a bigger change though since it alters existing functionality

**Comment by WillDaSilva** [comment]
@cjohnhanson @tayloramurphy Was there another issue created after this for essentially the same feature? I vaguely remember such an issue, but I haven't been able to find it.

**Comment by tayloramurphy** [comment]
@WillDaSilva I'm not aware of another issue except for the relevant internal product issue:

* https://github.com/meltano/internal-product/issues/210
