### ISSUE TITLE
Remove the deprecated UI and API

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6959]
In https://github.com/meltano/meltano/pull/6955 we removed the documentation around the UI. At some point we can slim down the codebase and the backend database by removing that code as well.

**Comment by aaronsteers** [comment]
Thanks for logging this, @tayloramurphy. 

I would want to do this alongside a major version bump to `3.0`, and probably also would want to make sure we have a path forward for the REST API (Meltano Server, or similar, as we're discussing elsewhere) before we fully remove.

A period of comments and discussion from community members would be a good help too, since there are likely use cases we can prioritize into interactive CLI experiences, per any specific feedback of roles that the UI is fulfilling today.
