### ISSUE TITLE
Pull Request Preview Environments for increasing maintainer productivity

### ISSUE THREAD

**Issue by waveywaves** [meltano/meltano#7042]
I would like to make life easier for Meltano maintainers by implementing [Uffizzi](https://github.com/UffizziCloud/uffizzi) preview environments. 
Disclaimer: I work on [Uffizzi](https://github.com/UffizziCloud/uffizzi). 

Uffizzi is a Open Source full stack previews engine and our platform is available completely free for Meltano (and all open source projects). This will provide maintainers with preview environments of their PRs in the cloud, allowing them iterate faster and reduce time to merge. You can see the open source repos which are currently using Uffizzi over [here](https://uffizzi.notion.site)

Uffizzi is purpose-built for the task of previewing PRs and it integrates with your workflow to deploy preview environments in the background without any manual steps for maintainers or contributors.

I can go ahead and create an Initial PoC for you right away if you think there is value in this proposal.

TODO:
- [ ] Intial PoC

**Comment by WillDaSilva** [comment]
Hi @waveywaves. Given Meltano's nature as a CLI program and data-engineering platform, I'm not sure what benefit we would get from Uffizzi. We already have per-PR preview environments for our documentation site, and we also run integration tests for every PR.

What specifically would the Uffizzi preview environment show PR reviewers in our case? Would it be an interactive command-line environment (via SSH) in which reviewers could try out the changes? If we wanted that, why should we prefer Uffizzi over a [GitHub Deployment](https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions) into a preview environment - a pattern we already use for https://github.com/meltano/squared?

**Comment by WillDaSilva** [comment]
Thanks for explaining @waveywaves. I can see this being useful for reviewing Meltano PRs, so I'll gladly take up your offer for a PoC.

Are we able to run an entry script for each of these PR environments? It is not crucial, but it might be nice if we could have the environment create a Meltano project automatically before the reviewer used the CLI.

Can we set environment variables in these PR environments?

What happens if multiple reviewers all try to access the CLI at the same time?
