### ISSUE TITLE
bug: Error: Setting value set via multiple environment variables: ['MELTANO_STATE_BACKEND_S3_AWS_ACCESS_KEY_ID', 'AWS_ACCESS_KEY_ID']

### ISSUE THREAD

**Issue by asmisha** [meltano/meltano#7059]
### Meltano Version

2.10.0

### Python Version

3.9

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Docker image meltano/meltano:v2.10.0-python3.9 run in AWS ECS FARGET Linux family

### Description

I keep getting this error
Error: Setting value set via multiple environment variables: ['MELTANO_STATE_BACKEND_S3_AWS_ACCESS_KEY_ID', 'AWS_ACCESS_KEY_ID']

MELTANO_STATE_BACKEND_S3_AWS_ACCESS_KEY_ID is never set
AWS_ACCESS_KEY_ID is set

**Comment by tayloramurphy** [comment]
@asmisha can you share:

* your meltano.yml
* which connector(s) you're seeing this error occur
* the commands you're running when you see this error

Thanks!

**Comment by asmisha** [comment]
@tayloramurphy 

- https://pastebin.com/KaTj6nUw
- it's global - doesn't let me use any of the meltano cli commands
- any command like 'schedule run' or 'invoke airflow pools set dbt 1 dbt'

**Comment by tayloramurphy** [comment]
@asmisha thanks for sharing. @cjohnhanson can you take a look at this since it's referencing the state backend environment variable?

**Comment by cjohnhanson** [comment]
@asmisha thanks for logging this. It could be that ECS is setting those environment variables in the container environment at runtime. [These docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html) seem to indicate that, though I could be misunderstanding  (CC: @magreenbaum -- could you confirm?)

If the tasks are assuming an IAM role which gives them access to the S3 bucket you're using to store state, you can just unset those two`MELTANO_STATE_BACKEND_S3_AWS_ACCESS_*` variables and Meltano will fall back to the boto3 to access S3. 

@tayloramurphy the reason this is happening is because we have `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` aliased to these state backend setting env vars. What are your thoughts on removing that explicit alias? The behavior would be very similar, since Meltano uses boto3 under the hood, which will fall back to those `AWS_*` env vars for authentication, but they wouldn't show up in `meltano config ...` or otherwise be managed by Meltano.

**Comment by tayloramurphy** [comment]
@cjohnhanson I think that would make sense. I'm not 100% sure of the downside of doing this, but seems like it would avoid this problem. @aaronsteers ?

**Comment by aaronsteers** [comment]
Agreed. If the user sets the MELTANO_ version, we should use it. Otherwise I think it's pretty standard to not parse AWS_ACCESS_KEY_ID and instead just let boto pick them up if they are needed.

**Comment by magreenbaum** [comment]
@cjohnhanson  you're correct. For fargate, if there's an IAM [task role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) associated with the task definition, the container gets the credentials it needs from there.

**Comment by cjohnhanson** [comment]
@tayloramurphy @aaronsteers FYI I've removed the explicit alias in #7078 

@asmisha -- takeaway here is that if there's an IAM task role associated with the task definition which has the proper S3 access, you can just omit these `MELTANO_STATE_BACKEND_` environment variables from the container runtime environment. Otherwise, the next Meltano release will have this fix that will support having both `MELTANO_STATE_BACKEND_AWS_ACCESS_KEY_ID` _and_ `AWS_ACCESS_KEY_ID` environment variables present in the runtime environment and this issue should go away.
