### ISSUE TITLE
Feature flag to disallow Meltano calling Hub outside of `add` and `discover`

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#7095]
### Meltano Version

2.11.1

### Python Version

NA

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

NA

### Description

With the recent switch to API Gateway and Netlify redirects, users that had whitelisted the now legacy Hub API (`https://hub.meltano.com/meltano/api/v1/`) are seeing failures because of the redirect to the Gateway endpoint.

See https://meltano.slack.com/archives/C01TCRBBJD7/p1671112207278089.

---

Back when I implemented `meltano add` from Hub, I decided to allow calls outside of `add` and `discover`, so users not yet onboarded to lockfiles would still be able to use their plugins without having to add those to a custom `discovery.yml`.

This can be disabled (as a breaking change) in our next major release (3.0).

**Comment by WillDaSilva** [comment]
Relates to:
- https://github.com/meltano/meltano/issues/6754

**Comment by aaronsteers** [comment]
> Back when I implemented meltano add from Hub, I decided to allow calls outside of add and discover, so users not yet onboarded to lockfiles would still be able to use their plugins without having to add those to a custom discovery.yml.
>
> At this point, we should probably disable that behavior and have Meltano fail when a plugin is not custom and doesn't have a lockfile.

@edgarrmondragon - I think we have to hold this until 3.0, if it would break existing users (and there are a lot) who have not yet locked their plugin files. Can you confirm?

I think there was a decision at some point to allow plugins to get their definitions from the hub (if not locked) vs getting from `discovery.yml`. But reverting to a check against the bundled or web-served `discovery.yml` would also be a breaking change at this point, since there's likely been significant drift and bug fixes on the Hub that users have already adapted to.
