### ISSUE TITLE
Add is_codespaces to telemetry environment context

### ISSUE THREAD

**Issue by DouweM** [meltano/meltano#7175]
Just like [we set `is_ci_environment` when the `CI` env var is set](https://github.com/meltano/meltano/blob/main/src/meltano/core/tracking/contexts/environment.py#L57), we should set `is_codespaces` (or something to that effect) when `CODESPACES` is set (see [docs](https://docs.github.com/en/codespaces/developing-in-codespaces/default-environment-variables-for-your-codespace)).

@tayloramurphy It'd be interesting to compare how far people get into the funnel with codespaces vs having to install locally. On the one hand, the barrier is lower so some people that click the button may be less motivated to make it to the end, but on the other hand, it should be easier to just quickly follow the steps and get to "wow". We may run into the issue that we currently consider any usage of less than 5min a bot, and that these codespaces projects may be treated as one-offs instead of being reused to form the company's official Meltano projects, so they'll never turn active. It'll be good to have the option of treating new codespaces projects differently from new local projects in our reporting.

**Comment by WillDaSilva** [comment]
This sounds like a good bit of data to collect, and while we're at it I'd also like to generalize the collection a bit here so that in the future we don't have to update a telemetry schema to collect more info about which env vars are truthy.

We can store a list of env vars including `GITHUB_ACTIONS`, `CI`, `CODESPACES`, etc. in `meltano.core`, and then report a dict of those which were present with Snowplow mapped to what their actual values were.
