### ISSUE TITLE
feature: AMI for fast deployment onto AWS

### ISSUE THREAD

**Issue by sbalnojan** [meltano/meltano#7193]
### Feature scope

Other

### Description

**Job Story:**
As a new Meltano user, when doing a PoC or deploying my first projects into production, I would love to have an AMI ready inside the AWS marketplace so that I can effectively do a "one click deployment of Meltano" for my purposes (for the first 1-2 years...). 

**Context:**
- AWS is the biggest cloud provider
- The "single fat instance" deployment is easy to do and favored by quite a few long time Meltano users
- AWS AMIs are a really easy way of getting started
- AWS AMIs are common among other OS projects, see e.g. https://redash.io/help/open-source/setup#aws

@tayloramurphy @aaronsteers

**Comment by tayloramurphy** [comment]
We used to have a Digital Ocean droplet for a while.

**Comment by aaronsteers** [comment]
The previous DigitalOcean implementation was dropped because of low usage and difficult maintenance/test profile.

I don't see a strong case for supporting EC2 while it's just as easy for users to create a long-lived ECS container these days. I'd also be concerned that support and maintenance will pull us away from other critical deliverables.

While it's easy enough to create a single AMI, that doesn't cover security review, template creation, docs authoring and maintenance, patching and updating the image, and then customizing/debugging the deployment with supporting services like Postgres or similar.

Are there generic templates that could serve this need? Or could we pick this up for consideration after Cloud GA perhaps?

**Comment by sbalnojan** [comment]
@aaronsteers I'm interested in your comment "just as easy to to create long-lived ECS containers".

I'm not 100% up to the AWS features, so I'm just curious. The last time I checked deploying an Meltano AMI would literally mean 1. upload your SSH key 2. click a button inside the AMI Marketplace.

The ECS task sounds harder to do, but as said, I haven't deployed any from the UI to be honest, maybe it's just as easy?

**Comment by tayloramurphy** [comment]
Still relevant, but a lower priority at the moment.
