### ISSUE TITLE
chore: run the auth callback server via, e.g., aiohttp rather than flask

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#7470]
We currently run the auth callback server via a dead-simple subprocess `flask` command call. This has already proven to be a bit fragile and difficult to test. Running the server async in the same process is a cleaner, more robust, and more testable solution.

**Comment by WillDaSilva** [comment]
@cjohnhanson @edgarrmondragon @aaronsteers As an added benefit, this will let us remove our dependency on Flask. Since [Werkzeug is only used in `meltano.api`](https://github.com/meltano/meltano/pull/7374), and by Flask, we'll be able to drop that troublesome dependency too.

A quick check with `poetry export` shows that we rely on 21 fewer dependencies (103 -> 82) simply by removing our dependencies on Werkzeug and dependencies with "flask" in their name.

A quick search of the code finds no usage of Flask outside of what will be removed when the UI is removed, and the Cloud CLI (which is what this issue aims to remedy).
