### ISSUE TITLE
vulnerability: werkzeug 2.1.2 (CVE-2023-25577)

### ISSUE THREAD

**Issue by hazmei** [meltano/meltano#7506]
### Feature scope

Other

### Description

We are currently testing meltano version 2.17.0 on our staging environment. Our vulnerability scanner (Trivy) detected a high severity for [Werkzeug dependency](https://github.com/meltano/meltano/blob/a0151ac42980a32d66c523ae20b9e4b01b94d467/poetry.lock#L3846-L3848) that is used in this project.

Link to the CVE:
- https://avd.aquasec.com/nvd/2023/cve-2023-25577/
- https://github.com/advisories/GHSA-xg9f-g7g7-2323

I saw that [dependabot opened a PR to bump Werkzeug from 2.1.2 to 2.2.3](https://github.com/meltano/meltano/pull/7326) which would fix this vulnerability. Would you be able to update this package? Thanks in advance!

**Comment by WillDaSilva** [comment]
Thank you for the report @hazmei 

We have long-since wanted to update our dependency on Werkzeug (in no small part to address the CVE), but have struggled to do so due to the restraints imposed by various other dependencies, and because of our own use of removed/changed parts of the library. We would have to make significant changes to the code that provides the Meltano UI.

The Meltano UI has been deprecated, and is scheduled for [removal in Meltano 3.0](https://github.com/meltano/meltano/pull/7499). We will no longer depend on Werkzeug in Meltano 3.0 onward.

I do not expect we'll be able to update our Werkzeug dependency to version 2.2.3 before Meltano 3.0.

If you're not using the Meltano UI, you should be safe to ignore the CVE if that is an option available to you.

If you're not able to ignore the CVE, and waiting for the release of Meltano 3.0 (exact release date unknown - probably sometime this summer) is not an option, then another option could be using an unreleased development version of Meltano by depending directly on our Git repository instead of depending on a published version from PyPI. The Werkzeug dependency will likely be removed from our `cloud` branch this week as part of the PR linked above. This comes with all the usual risks of depending on an unreleased development version of an application :sweat_smile:

Another option would be to contribute the fix yourself, which we'd be happy to accept. I've added the `Accepting Pull Requests` label to this issue to reflect that.

**Comment by WillDaSilva** [comment]
This could also be worked around by:
- https://github.com/meltano/meltano/issues/7006

That way all dependencies exclusive to the UI like Werkzeug would become optional. The vulnerability scanner would probably still flag Meltano as having dependencies with known security issues, but not installing those dependencies would be possible, and the default behaviour.

**Comment by edgarrmondragon** [comment]
Werkzeug is no longer a runtime dependency of Meltano. It's still present in `poetry.lock` as a transitive dependency via [moto](https://github.com/getmoto/moto) and [pytest-httpserver](https://github.com/csernazs/pytest-httpserver), and even there it's already at `2.3.7`.

I think we can consider this resolved.
