### ISSUE TITLE
cloud cli deployment filtering for non-workload commands

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7731]
Previous context is in https://github.com/meltano/meltano/pull/7729#issuecomment-1572654324

This was my opinion:

> personally I do think it should affect all commands with a --deployment option. If I have multiple deployments and I set my context to use one of them I would expect everything that I interact with would have that deployment pre-selected. I've been thinking of these deployments as completely isolated from each other. Similar to git when I chose a branch I wouldnt expect to see anything related to any other branches other than the one I'm on.

A few thoughts following on from that thread:

I find it unintuitive that when I `use` a deployment it is sticky for some but not all commands. Also when I `use` a project it is sticky so it feels inconsistent across project/deployment commands, like `meltano-cloud schedule list` will prefilter for my active project but not my active deployment. It also seems like we're setting the CLI up to let users interact with all of cloud at once but from a user perspective I feel like I'll only ever be interacting with a single deployment and project at one time. Like right now when I list my schedules I see staging and prod mixed but I dont care about staging at all. Similarly I list my history and I see staging jobs but those dont matter to me. Eventually I'll probably have CI jobs running too so mixing those with my prod jobs will become extra noisey.

**Comment by tayloramurphy** [comment]
So I spent a little time in [Miro whiteboarding](https://miro.com/app/board/uXjVMC6Ge4I=/) out the different commands and our information hierarchy. When we project forward to when we add support for multiple organizations some things will likely be true:

* we'll have commands for org switching and management - `meltano cloud org use --name <>
* we'll likely want to require the user to select their org before they can do anything else besides login or out. if they have one org, then it would default to that automatically

Once a user is `use`ing a specific org, then all commands run in the context of that org - makes sense I think. 

So now let's say an org has 2 projects, each with 2 deployments (4 deployments in total). Each running their own set of schedules. 

At the org level, we have the `project` command which is used for listing projects and switching between projects. 

We also have `config` which sets secrets at an org-level. In the future we will want to expand its scope to enable settings at the project and deployment levels.

`history` is currently a project-level command b/c it (afaik) currently requires a project to be selected before it returns data. There is a valid use case for wanting to understand at a high level how all deployments/schedules across all projects are generally performing. But `history` is likely _not_ the right command or interface for this in the longterm. (I like my `status` placeholder where users could get a quick summary of what's happened.) 

So, a couple of things fall out of this hierarchy for me because of this. 

* I've reversed my position and I would agree with Pat - if a user `use`s a project and a deployment, all relevant commands should be using them as if they were passed as args. 
* This does mean, however, that we need to make it clear to users which ones they have selected - so on the CLI we need to print `Using X project and Y Deployment` or something similar. 
* We could have an option to `--unset` the choice for project and deployment, but perhaps that's not useful. But once you select a deployment it's not clear how you unselect one
* `history` could be brought _up_ to the org-level by either allowing for a --all flag or by `--unset`ing the project and deployment - but this would be lower priority
* `config` will be expanded over time to allow settings at project, deployment, and possibly schedule levels - this means it would need to `use` the default project and deployment as well.
* The only things that might not make sense for project/deployment usage would be billing - because of this I'm leaning towards having billing under an org subcommand - `meltano cloud org billing/usage`. It's going to be a more common use case to need to know the billing/usage status across the entire org than at the project level. that said, we could do `cloud billing/usage`, respect the flags, and have an `--all` flag that returns it for everything. TBD on that spec, but I want the general assumption that `use` is across all relevant commands to hold.

-----

Ok, so that's a lot. Relevant actions depending on discussion:

- [ ] Issue for noting on the CLI what project and deployment is selected
- [ ] Issue for updating `history` to use project and deployment defaults
- [ ] Issue for adding `--all` to history flag (or consider --unset)
- [ ] Issue for expanding config options (Roadmap level)
- [ ] Update issue around billing user stories / requirements

@pnadolny13 @WillDaSilva am I missing anything? Please push back if you think I'm offtrack here.

**Comment by tayloramurphy** [comment]
Ping on the above @WillDaSilva @pnadolny13

**Comment by pnadolny13** [comment]
@tayloramurphy I agree with what you laid out.

- Definitely having https://github.com/meltano/infra/issues/1254 is important so users arent running or making changes unexpectedly.
- I like the idea of filtered history to the project/deployment level by default with the option to run it with an explicit `--deployment=x --project=y` override or `--all` to get everything at the org level.

>I like my status placeholder where users could get a quick summary of what's happened.



The `status` command ([isssue](https://github.com/meltano/meltano/issues/6958)) makes sense to me here in the [session status context](https://github.com/meltano/meltano/issues/6958#issuecomment-1551621181). It could tell me what sticky selections I've made and maybe some other minor details. For more in depth summaries I like a standalone summary command to show things like healthy pipelines, failure counts, schedules active/inactive, etc.

**Comment by WillDaSilva** [comment]
@tayloramurphy That all makes sense to me.

I wish we used a better CLI library instead of Click so that we could easily make all commands have `--project` and `--deployment` parameters that override the defaults set by the `use` commands. Being consistent with this across all of our CLI commands will be tricky, and I expect there will be more than a few rough edges.
