### ISSUE TITLE
feature: programmatic invocation of meltano cli

### ISSUE THREAD

**Issue by bdewilde** [meltano/meltano#7769]
### Feature scope

API

### Description

dbt recently added ["programmatic invocation"](https://docs.getdbt.com/reference/programmatic-invocations) functionality, and I was hoping to leverage for a dbt project embedded within a larger meltano project. Is that possible? I've looked through meltano's docs / web search, but haven't found any examples. I know meltano is very focused on the CLI interface, but providing a Python-based entry point to that interface could be useful. In fact it would, in my case.

**Comment by bdewilde** [comment]
Hi @WillDaSilva , I did see that other issue, but didn't think they were the same: I'm talking about a Python entry point to meltano's CLI in the same spirit as dbt's, while that seems to be about a Python package for meltano's underlying core functionality. No worries, totally understand the need to prioritize!

**Comment by WillDaSilva** [comment]
My bad @bdewilde. This seems like a great idea, and wouldn't be too difficult.

**Comment by edgarrmondragon** [comment]
Happy to review a PR if someone has a use case that requires this change. As mentioned above, something like dbt's [task API pattern](https://github.com/dbt-labs/dbt-core/tree/main/core/dbt/task) might work here. Perhaps under `meltano.core.actions`:

```
src
└── meltano
    ├── __init__.py
    ├── actions
    ├── cli
    ├── core
    ├── migrations
    └── schemas
```

**Comment by edgarrmondragon** [comment]
Added the label https://github.com/meltano/meltano/labels/good%20first%20issue, cause although it's lot of grunt work of moving code around the task itself is fairly straightforward IMO.

**Comment by zim10** [comment]
Hi, I'd like to work on this. I'm planning to follow the dbt task API pattern under meltano.core.actions as suggested. Is this still available?

**Comment by evasafi** [comment]
Hi, I see @zim10 asked about this a few weeks back with no response yet. If they're still planning to pick it up, I don't want to duplicate effort. happy to collaborate or find something else. If it's actually still open, I'd like to take it on, following the meltano.core.actions / dbt task-API pattern @edgarrmondragon outlined. Would start by wrapping one or two CLI commands (e.g. run) as a proof of concept before expanding further.

**Comment by edgarrmondragon** [comment]
This is a foundational change to the project, so I've been hesitant to claim being able or willing to review any PR that comes trying to address it.

@zim10 @evasafi are you Meltano users? If so, can you explain your use case? I'd like this to be strictly driven by necessity and avoid tech-debt and establishing brittle contracts that bind us from future improvements.

The CLI is nice as an interface because we can refactor most things under the hood without breaking our contract. Having a public API makes that significantly more difficult and adds more friction to certain types of changes.

Yes, dbt has a task pattern but they've broken their public code many times within a single major version. See for example https://github.com/sqlfluff/sqlfluff, which has been forced to add handling for different 1.x versions.

Also, what if we want to (very hypothetically 😉) port Meltano to something like Rust?

**Comment by edgarrmondragon** [comment]
Case in point with regards to dbt's upcoming v2:

```console
$ uvx -q -p 3.13 --with 'dbt-core<2' python -c 'from dbt.cli.main import dbtRunner; dbt = dbtRunner(); dbt.invoke(["--help"])'
Usage: cli [OPTIONS] [COMMAND] [ARGS]...

$ uvx -q -p 3.13 --with 'dbt-core>=2.0.0.dev0' python -c 'from dbt.cli.main import dbtRunner; dbt = dbtRunner(); dbt.invoke(["--help"])'  <aws:sandbox> <region:us-west-2>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from dbt.cli.main import dbtRunner; dbt = dbtRunner(); dbt.invoke(["--help"])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'dbt'
```

i.e. they're breaking their [documented programmatic invocations](https://docs.getdbt.com/reference/programmatic-invocations?version=2.0&name=Fusion).

**Comment by evasafi** [comment]
Ah I see. Thanks for the context, that dbt v2 example makes your concern really concrete. To answer honestly, I don't have a production use case driving this I came across the issue as someone looking to contribute and found the pattern interesting. Given the real risk of locking in a brittle public API contract I don't think I'm the right person to push this forward without genuine necessity behind it so I'll hold off. Happy to look at something else in the meantime.

**Comment by edgarrmondragon** [comment]
Thanks @evasafi, I've labeled some other issues with https://github.com/meltano/meltano/labels/good%20first%20issue so feel free to look at those.

**Comment by zim10** [comment]
Thanks for the context @edgarrmondragon. To be honest, I don't have a production use case for this either — I asked about it out of general interest, not because I'm currently blocked by something. Given the concerns you raised about API stability, I don't think I'm the right person to push this forward. Happy to look at one of the "good first issue" tickets instead if you can point me to them.
