### ISSUE TITLE
bug: Tap's stderr is lost in `meltano config test`

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8307]
### Meltano Version

3.2.0

### Python Version

3.6 (deprecated)

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

NA

### Description

Following https://github.com/meltano/meltano/pull/8225, we started sending the tap's stderr to /dev/null. Some error information in that stream may be useful, so it's probably worth revisiting and maybe redirector to stderr instead.

**Comment by ReubenFrankel** [comment]
@edgarrmondragon I'd like to pick this up, but what does success look like here? If we pipe stderr through it will pollute the command output, and if we expose it as debug log messages then we run into the decoding problem from #8223 originally.

Also, the accompanying [last line](https://github.com/meltano/meltano/blob/6e684f233961be1f1b37550fa0f855e3bc097244/src/meltano/core/plugin_test_service.py#L107) message to "Plugin configuration is invalid" is now usually less helpful than before #8225, since only stdout is considered:

**Before**
![image](https://github.com/meltano/meltano/assets/60552974/d8d4352d-b215-47ca-b29e-709f7af30f97)

**After**
![image](https://github.com/meltano/meltano/assets/60552974/2ff731bc-6f24-491c-94b1-355424cd7ea4)

**Comment by edgarrmondragon** [comment]
> and if we expose it as debug log messages then we run into the decoding problem from #8223 originally.

@ReubenFrankel I wonder if we can get rid of the ascii-decoding step. I'm trying to figure out why it was done in the first place (https://gitlab.com/meltano/meltano/-/merge_requests/2326/diffs#eb41602e1cb2d08c869f29666c89d2ee08a97b26_0_61), but I'm afraid it's a Chesterton’s Fence situation 😅.

**Comment by ReubenFrankel** [comment]
`utf-8` seems to work better here, along with change from #8225 backed out:

![image](https://github.com/meltano/meltano/assets/60552974/9fd15b5b-31d5-482a-8ff7-f24c6c58e017)

I tested with `tap-jaffle-shop` and it works:

```
meltano config tap-jaffle-shop test
```
![image](https://github.com/meltano/meltano/assets/60552974/8bc473e1-5be3-4e88-b3ac-1fa88ebc6ed8)

```
meltano --log-level debug config tap-jaffle-shop test
```
![image](https://github.com/meltano/meltano/assets/60552974/188c2d0a-0691-43f7-a961-c75944dcad7b)

and `tap-spotify` (test with bad config) for good measure:

```
meltano config tap-spotify test
```
![image](https://github.com/meltano/meltano/assets/60552974/b83a47de-6466-4484-a48b-c08192ffe619)

**Comment by ReubenFrankel** [comment]
`utf-8` seems to work better here, along with change from #8225 backed out:

![image](https://github.com/meltano/meltano/assets/60552974/9fd15b5b-31d5-482a-8ff7-f24c6c58e017)

I tested with `tap-jaffle-shop` and it works:

```
meltano config tap-jaffle-shop test
```
![image](https://github.com/meltano/meltano/assets/60552974/8bc473e1-5be3-4e88-b3ac-1fa88ebc6ed8)

```
meltano --log-level debug config tap-jaffle-shop test
```
![image](https://github.com/meltano/meltano/assets/60552974/188c2d0a-0691-43f7-a961-c75944dcad7b)

and `tap-spotify` (test with bad config) for good measure:

```
meltano config tap-spotify test
```
![image](https://github.com/meltano/meltano/assets/60552974/b83a47de-6466-4484-a48b-c08192ffe619)

What do you think? @edgarrmondragon

**Comment by edgarrmondragon** [comment]
@ReubenFrankel Thanks for running the experiment! That works for me 🙂
