### ISSUE TITLE
feature: `meltano state clear --all` argument

### ISSUE THREAD

**Issue by fauzxan** [meltano/meltano#8749]
# Feature scope

CLI (options, error messages, logging, etc.)

# Context

Need the ability to clear all states. In particular, currently if one wants to automate the clearing of states table, we are required to 
1. list all the states using `meltano state list`
2. then use this list to loop through all the states and run `meltano state clear --force {state}` for each state

One can carry out the above, with either CLI, or python code:

### CLI
```shell
meltano state list | xargs -I {} sh -c 'meltano state clear --force {}`
```

### Python
```python3
state_ids = subprocess.run(
        [
            "meltano",
            "state",
            "list"
        ]
    )
    
state_list = state_ids.stdout.split('\n')
state_clear_command = ';'.join([f"meltano state clear --force {state}" for state in state_list if state])
subprocess.call(state_clear_command, shell=True)
```
# Request

It would be convenient if someone could help introduce the functionality to add `--all` flag for meltano state command. 

I believe we could modify this part of the code: https://github.com/meltano/meltano/blob/2f53237190ca463292dfe67d2b93731968fdc6ab/src/meltano/cli/state.py#L311-L321

to accept a new parameter `--all` that:
1. Carries out a intention check `Are you sure you want to do this?` which can be overridden with `--force` option
2. Then loops through all the states and clears them

I need assistance in confirming if this is the right part of the code to modify for this purpose. 

I would be happy to know any alternative approaches to this as well! If there are any workarounds for this currently, do let me know!

**Comment by edgarrmondragon** [comment]
Hi @fauzxan!

This makes sense and it would indeed by a of nuisance to have to write a script that iterates over state IDs to clear all of them.

A few things need to happen in order to support this:

1. Make the `state-id` argument of `meltano clear` optional and add the `--all` option.
2. Update `StateService` and the `StateStoreManager` interface to support clearing all state IDs.
3. Implement the new interface in all state store managers.
4. Use the new `StateService` to clear all IDs if `--all` is passed.

I added the https://github.com/meltano/meltano/labels/Accepting%20Pull%20Requests label, in case you or someone else is interested in contributing before we prioritize this internally.

**Comment by edgarrmondragon** [comment]
Sharing here from Slack:

<blockquote>

We could add a default `clear_all()` implementation in the base `StateStoreManager` to get this out of the door, and then create a task list issue to track implementations of store-specific bulk deletion where it's applicable.

</blockquote>
